### PR TITLE
Fixes: <Issue #9811> optimize password reg

### PR DESCRIPTION
**Pull request by ghost**
It would be more convenient to support @ in password by optimize the reg

### Description
url reg for password

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [x] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks, but as mentioned in the issue the current behaviour is expected

**Comment by CaselIT** [comment]
interesting, this may actually work. cc @zzzeek can you take a look?

**Comment by zzzeek** [comment]
can you find the original issue?

**Comment by zzzeek** [comment]
well no need, it obviously fails tests .   we didn't just phone this one in, it was a big deal

**Comment by zzzeek** [comment]
hi -

This PR does not follow the [guidelines](https://github.com/sqlalchemy/sqlalchemy/blob/main/.github/pull_request_template.md) for PR submissions:

1. the "feature" box is checked, but the issue number as requested in the box is not present.  we require an issue be created first.
2. no issue was created
3. no tests

beyond that, the change here fails current tests.     See #6482 as well as [rfc 1738](https://datatracker.ietf.org/doc/html/rfc1738#section-3.1) upon which our URL scheme is loosely based.

before:

```py
>>> from sqlalchemy import make_url
>>> u1 = make_url("mssql://user:pass@host/database@x1")
>>> u1.database
'database@x1'
```

with PR

```py
>>> from sqlalchemy import make_url
>>> u1 = make_url("mssql://user:pass@host/database@x1")
>>> u1.database

```

**Comment by CaselIT** [comment]
Btw the issue was opened, but I guessed it would bot work https://github.com/sqlalchemy/sqlalchemy/issues/9811

Thanks in any case @lijiaweinpc

**Comment by CaselIT** [comment]
> interesting, this may actually work

Forgot that db names can have @ too.
It may be impossible to parse this with a regexp while allowing @ in passwords

**Pull request closed without merging**
