### PR TITLE
set type of type_of to be same as input argument

### LINKED ISSUE #11371: Typing: of_type method not properly generic.
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

of_type() method for QueryableAttribute is not properly made generic. This causes the type to not be set correctly and the result is not completely determined. This is only a minor nuisance  as the correct type is not needed for any other checking.

### To Reproduce

```python
# pyright: strict
from typing import reveal_type

from sqlalchemy import create_engine, ForeignKey
from sqlalchemy.orm import (
    scoped_session,
    sessionmaker,
    DeclarativeBase,
    MappedAsDataclass,
    mapped_column,
    Mapped,
    relationship,
)

engine = create_engine("sqlite://")
db_session = scoped_session(sessionmaker(engine))


class Base(MappedAsDataclass, DeclarativeBase):
    pass


class Employee(Base):
    __tablename__ = "employee"
    id: Mapped[int] = mapped_column(primary_key=True)
    team_id: Mapped[int] = mapped_column(ForeignKey("team.id"))
    team: Mapped["Team"] = relationship(
        lazy="noload", init=False, back_populates="employees"
    )

    __mapper_args__ = {
        "polymorphic_on": "type",
        "polymorphic_identity": "employee",
    }


class Team(Base):
    __tablename__ = "team"
    id: Mapped[int] = mapped_column(primary_key=True)
    team_name: Mapped[str]
    employees: Mapped[list[Employee]] = relationship(
        "Employee", lazy="noload", init=False
    )


class Engineer(Employee):
    engineer_info: Mapped[str | None] = mapped_column(nullable=True, default=None)

    __mapper_args__ = {
        "polymorphic_identity": "engineer",
        "polymorphic_load": "inline",
    }


engineer_load = Team.employees.of_type(Engineer)
reveal_type(Team.employees.of_type(Engineer))
```

### MYPY

of_type_test.py:55: error: Need type annotation for "engineer_load"  [var-annotated]
of_type_test.py:56: note: Revealed type is "sqlalchemy.orm.attributes.QueryableAttribute[<nothing>]"

### Pyright

.\of_type_test.py:55:1 - error: Type of "engineer_load" is partially unknown
    Type of "engineer_load" is "QueryableAttribute[Unknown]" (reportUnknownVariableType)
.\of_type_test.py:56:13 - information: Type of "Team.employees.of_type(Engineer)" is "QueryableAttribute[Unknown]"

### Versions

- OS: Windows 11
- Python: 3.11 and 3.12
- SQLAlchemy: 2.0.30
- Type checker: mypy 1.10.0 and pyright 1.362

### Additional context

Changing signature of the of_type method seems to fix it. 

from: 
    ` def of_type(self, entity: _EntityType[Any]) -> QueryableAttribute[_T]:`
to
   ` def of_type(self, entity: _EntityType[_T]) -> QueryableAttribute[_T]:`

Mypy: 
of_type_test.py:56: note: Revealed type is "sqlalchemy.orm.attributes.QueryableAttribute[of_type_test.Engineer]"
Pyright:
\of_type_test.py:56:13 - information: Type of "Team.employees.of_type(Engineer)" is "QueryableAttribute[Engineer]"

### PR DESCRIPTION
**Pull request by WAKayser**
Closes: #11371

Fixes the of_type method so that it does not return a class with unset generic. 
See the original issue for a more detailed explanation.

### CODE REVIEW

**Comment by CaselIT** [comment]
thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision ed8d0edebb6b84b9dcffcf24c52f113c37e7fedd of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change ed8d0edebb6b84b9dcffcf24c52f113c37e7fedd: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5401

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

great, thanks

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5401

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5401 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5404 has been **merged**. Congratulations! :)

**Pull request closed without merging**
