### PR TITLE
Updated typing for self_group()

### PR DESCRIPTION
**Pull request by MarkWine**
### Checklist

This pull request is:

- [x] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by MarkWine** [comment]
I've removed the extra return typing for now - I believe there might be different behavior for each - it seems like just the generic `-> ClauseElement` or even `-> Self` would be close to correct, but not quite there.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 3ebf4db506ffef629f938f4f36fc76d6671b98e1 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 3ebf4db506ffef629f938f4f36fc76d6671b98e1: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5288

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

OK I was confused because the test shown at  https://github.com/sqlalchemy/sqlalchemy/issues/10939 has a typing error in that it re-uses "test", so it fails, fixing that though this patch works

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5288

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5290 has been **merged**. Congratulations! :)

**Pull request closed without merging**
