### PR TITLE
Fixes minor typo

### PR DESCRIPTION
**Pull request by amarvin**
### Description

Fixes a minor typo in one heading of the docs, to have correct uppercase characters.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by jvanasco** [comment]
This is the only occurrence of "Urls", however there are a few references to "url" and "urls" across all documentation as plaintext (and not referencing a "url" attribute).

@CaselIT what is your opinion on standardizing the terms?

**Comment by CaselIT** [comment]
sure, let's go for it, since it's the odd man out

**Comment by jvanasco** [comment]
> sure, let's go for it, since it's the odd man out

but what about the "url" and "urls" in the docs? Should they all become "URL" and "URLs" ?

**Comment by CaselIT** [comment]
I guess it depends if they refer to the URL class or not

**Pull request merged**
