### PR TITLE
Refactor and Improve Readability of Code Formatting Function

### PR DESCRIPTION
**Pull request by gustavosett**
This commit refactors the main code formatting function by breaking down the process into more manageable parts. The new function, _format_block(), is introduced to handle the formatting of individual blocks of code.

This refactoring helps to increase the clarity of the code and improve its maintainability. Extensive comments and detailed docstrings have been added throughout to further enhance the readability and to provide a better understanding of the code flow and logic.

Note that this change focuses primarily on improving the readability of the code, and does not include performance optimization efforts as these require a more in-depth understanding of the context and execution profile data.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks, but no thanks.

This change completely breaks the indentation. It's also an internal tool that does not really need documentation.

If this was done with automated tools, like GPT or copilot, it would be appropriate to say so

**Comment by gustavosett** [comment]
I'm new at this, i'm just trying to help. To be honest, I did have some help from the gpt, but I was just trying to help, sorry I thought I could improve on something.

**Comment by CaselIT** [comment]
Well for a start you could have tried to see if the change had some unintended effect.

This currently changes the formatting of every doc file, while it's supposedly only adding documentation..

**Comment by gustavosett** [comment]
Ok! One day I'll try improve in something. Again, sorry for that.

**Pull request closed without merging**
