### PR TITLE
Correct type hint for FunctionElement.table_valued()

### PR DESCRIPTION
**Pull request by mjpieters**
### Description

The documentation and the type annotations for `TableValueType()` clearly
state that both strings and column expression arguments are accepted
but the annotation omits `str`, which is the most common use case.

### Checklist
This pull request is:

- [x] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Review by CaselIT — CHANGES_REQUESTED** [review]
just a suggestion to re-use an existing alias

**Comment by CaselIT** [comment]
Thanks for the update.
Sorry I forgot to mention in the previous review, could you add a "typing test" here `test/typing/plain_files/sql/functions_again.py`. Just calling table_valued with a string and a foo attribute should be ok to test both calling styles

**Comment by mjpieters** [comment]
> could you add a "typing test" here `test/typing/plain_files/sql/functions_again.py`. Just calling table_valued with a string and a foo attribute should be ok to test both calling styles

Thanks for the pointer, done!

**Comment by CaselIT** [comment]
Thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 624a97f051b378516518a30d88e7f216456d1c50 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 624a97f051b378516518a30d88e7f216456d1c50: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5110

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Is a chngelog needed? There isn't an issue for this.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5110

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

it's not critical but lets backport right

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5110

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

sure, I'll try doing that tomorrow

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5110

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

done

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5110

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

error is unrelated

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5117

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5110 has been **merged**. Congratulations! :)

**Pull request closed without merging**
