### PR TITLE
test update_nowait - added support in MariaDB-10.3

### PR DESCRIPTION
**Pull request by grooverdan**
### Description

MariaDB supported NOWAIT in 10.3.

ref: https://mariadb.com/kb/en/wait-and-nowait/

### Checklist

This pull request is:

- [X] very trivial test change
- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
No change is needed in the compiler? I don't remember if it's dialect specific or not

**Comment by CaselIT** [comment]
Thanks!

No change is needed in the compiler? I don't remember if it's dialect specific or not

I'll make it run on Jenkins

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 8af63436b704389f777b78e69e8ae9ba2204241f of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 8af63436b704389f777b78e69e8ae9ba2204241f: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3073

**Comment by grooverdan** [comment]
It passed the local testing against a 10.5 instance and it passed all the tests with nowait in the name.

**Comment by CaselIT** [comment]
I can reproduce the issue locally by running  `pytest --db mariadb .\test\orm\test_versioning.py -k test_versioncheck_for_update --log-info=sqlalchemy.engine`

The generated sql looks fine, so it's strange that no error is raised when another session tries to read a locked row

```
INFO:sqlalchemy.engine.Engine:SELECT version_table.id AS version_table_id, version_table.version_id AS version_table_version_id, version_table.value AS version_table_value
FROM version_table
WHERE version_table.id = %s
INFO:sqlalchemy.engine.Engine:[generated in 0.00031s] (1,)
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT version_table.id AS version_table_id, version_table.version_id AS version_table_version_id, version_table.value AS version_table_value
FROM version_table
WHERE version_table.id = %s
INFO:sqlalchemy.engine.Engine:[generated in 0.00027s] (1,)
INFO:sqlalchemy.engine.Engine:SELECT version_table.id, version_table.version_id, version_table.value
FROM version_table
WHERE version_table.id = %s FOR UPDATE
INFO:sqlalchemy.engine.Engine:[generated in 0.00031s] (1,)
INFO:sqlalchemy.engine.Engine:SELECT version_table.id, version_table.version_id, version_table.value
FROM version_table
WHERE version_table.id = %s FOR UPDATE NOWAIT
INFO:sqlalchemy.engine.Engine:[generated in 0.00029s] (1,)
```

Is this an isolation level issue?

**Comment by grooverdan** [comment]
Not the isolation level. The table it creates in the test is MyISAM. As its a transactional operation it needs InnoDB.

I'd hoped this would have been sufficient to switch its not changing it for me:
```
diff --git a/test/orm/test_versioning.py b/test/orm/test_versioning.py
index 54500e599..4cb9f90e4 100644
--- a/test/orm/test_versioning.py
+++ b/test/orm/test_versioning.py
@@ -80,6 +80,8 @@ class NullVersionIdTest(fixtures.MappedTest):
             ),
             Column("version_id", Integer),
             Column("value", String(40), nullable=False),
+            mysql_engine="InnoDB",
+            mariadb_engine="InnoDB",
         )
 
     @classmethod

```

**Comment by grooverdan** [comment]
My grossly brute force InnoDB forcing ensures this passes.
```
$  pytest --db mariadb ./test/orm/test_versioning.py -k test_versioncheck_for_update --log-info=sqlalchemy.engine
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00008s] ()
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] ()
======================================================================================== test session starts =========================================================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/dan/.py3/bin/python3
cachedir: .pytest_cache
rootdir: /home/dan/repos/sqlalchemy, configfile: setup.cfg
plugins: anyio-3.3.1, cov-2.12.1
collected 60 items / 59 deselected / 1 selected                                                                                                                                                      

test/orm/test_versioning.py::VersioningTest_mariadb+mysqldb_10_6_5_6_5::test_versioncheck_for_update PASSED                                                                                    [100%]

================================================================================== 1 passed, 59 deselected in 0.42s ==================================================================================
(.py3) 
~/repos/sqlalchemy mariadb_supports_nowait
$ git diff
diff --git a/lib/sqlalchemy/testing/schema.py b/lib/sqlalchemy/testing/schema.py
index 9c6bf9e4c..ccba68b25 100644
--- a/lib/sqlalchemy/testing/schema.py
+++ b/lib/sqlalchemy/testing/schema.py
@@ -46,7 +46,7 @@ def Table(*args, **kw):
             if "test_needs_fk" in test_opts or "test_needs_acid" in test_opts:
                 kw["mariadb_engine"] = "InnoDB"
             else:
-                kw["mariadb_engine"] = "MyISAM"
+                kw["mariadb_engine"] = "InnoDB"
 
     # Apply some default cascading rules for self-referential foreign keys.
     # MySQL InnoDB has some issues around selecting self-refs too.
```

**Comment by grooverdan** [comment]
helps when I fix the right test VersioningTest rather than NullVersionIdTest

**Comment by CaselIT** [comment]
> Not the isolation level. The table it creates in the test is MyISAM. As its a transactional operation it needs InnoDB.

Thanks for looking into it. I've never used mysql/mariadb much, so I'm not familiar with their behaviour.

Is the default table version myisam in the db or is it a sqlalchemy thing? (I guess cc @zzzeek )

I'll make it re-run the pipeline

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 4fa750e3d34638be7e9583d849216f6d90ca88fc of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 4fa750e3d34638be7e9583d849216f6d90ca88fc added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3073

**Comment by grooverdan** [comment]
> > Not the isolation level. The table it creates in the test is MyISAM. As its a transactional operation it needs InnoDB.
> 
> Thanks for looking into it. I've never used mysql/mariadb much, so I'm not familiar with their behaviour.

Here to help.

> Is the default table version myisam in the db or is it a sqlalchemy thing? (I guess cc @zzzeek )

MyISAM is sqlalchemy's default in lib/sqlalchemy/testing/schema.py

MariaDB's default is InnoDB - https://mariadb.com/kb/en/server-system-variables/#default_storage_engine

`test_needs_acid=True` also works.

> I'll make it re-run the pipeline

Thanks.

Pep8 fixes - see #7020

**Comment by zzzeek** [comment]
> > Not the isolation level. The table it creates in the test is MyISAM. As its a transactional operation it needs InnoDB.
> 
> Thanks for looking into it. I've never used mysql/mariadb much, so I'm not familiar with their behaviour.
> 
> Is the default table version myisam in the db or is it a sqlalchemy thing? (I guess cc @zzzeek )
> 
> I'll make it re-run the pipeline

myisam was the default in much older MySQL versions, but i think we are testing back to 5.6 where this may have been the case.  that said we should have innodb set as default in the container configs we use but i havent checked this.

**Comment by CaselIT** [comment]
> 
> 
> > > Not the isolation level. The table it creates in the test is MyISAM. As its a transactional operation it needs InnoDB.
> > 
> > 
> > Thanks for looking into it. I've never used mysql/mariadb much, so I'm not familiar with their behaviour.
> > Is the default table version myisam in the db or is it a sqlalchemy thing? (I guess cc @zzzeek )
> > I'll make it re-run the pipeline
> 
> myisam was the default in much older MySQL versions, but i think we are testing back to 5.6 where this may have been the case. that said we should have innodb set as default in the container configs we use but i havent checked this.

I think it would make sense to switch the default in the test then

**Comment by grooverdan** [comment]
Yes it was the default and even common usage at one stage. There are even still instances using it or MariaDB's replacement Aria in some use cases.

Even MySQL-5.6 storage engine defaulted to InnoDB (https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_default_storage_engine). I checked its container and its also InnoDB default too.

MyISAM seems to be much more on the way out in MySQL documentation. [MyISAM in MariaDB](https://mariadb.com/kb/en/myisam-storage-engine/) is discouraged in favour of Aria.

So I'd suggest:
```
diff --git a/lib/sqlalchemy/testing/schema.py b/lib/sqlalchemy/testing/schema.py
index 9c6bf9e4c..649613c65 100644
--- a/lib/sqlalchemy/testing/schema.py
+++ b/lib/sqlalchemy/testing/schema.py
@@ -33,10 +33,7 @@ def Table(*args, **kw):
             and "mysql_type" not in kw
             and "autoload_with" not in kw
         ):
-            if "test_needs_fk" in test_opts or "test_needs_acid" in test_opts:
-                kw["mysql_engine"] = "InnoDB"
-            else:
-                kw["mysql_engine"] = "MyISAM"
+            kw["mysql_engine"] = "InnoDB"
     elif exclusions.against(config._current, "mariadb"):
         if (
             "mariadb_engine" not in kw
@@ -46,7 +43,7 @@ def Table(*args, **kw):
             if "test_needs_fk" in test_opts or "test_needs_acid" in test_opts:
                 kw["mariadb_engine"] = "InnoDB"
             else:
-                kw["mariadb_engine"] = "MyISAM"
+                kw["mariadb_engine"] = "Aria"
 
     # Apply some default cascading rules for self-referential foreign keys.
     # MySQL InnoDB has some issues around selecting self-refs too.
```

To get slightly more coverage on MariaDB, enforce in CI of your MariaDB containers to be InnoDB with `--enforce-storage-engine=InnoDB`. This will be fixed in the next container release (https://github.com/MariaDB/mariadb-docker/commit/dc74f6bf4c85d327fa0fddabf698435e4e5faf1a) in  a week or so.

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3073 has been **merged**. Congratulations! :)

**Pull request closed without merging**
