### PR TITLE
doc change - Add new external dialect for openGauss

### PR DESCRIPTION
**Pull request by jiajunsu**
### Description

Added new external dialect for [openGauss](https://www.opengauss.org/en/).

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by shihai1991 — APPROVED** [review]
LGTM.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision ca5a7f1310b2ce93ce33618e0609abe23b41a3da of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by zzzeek** [comment]
sorry for the delay!

**Comment by sqla-tester** [comment]
New Gerrit review created for change ca5a7f1310b2ce93ce33618e0609abe23b41a3da: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4269

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4269 has been **merged**. Congratulations! :)

**Pull request closed without merging**
