### PR TITLE
Fixes: #4914 Amend BufferedRowResultProxy to handle max_row_buffer > …

### PR DESCRIPTION
**Pull request by sumau**
### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by sumau** [comment]
I tested it by checking the dashboard screen on PGAdmin and making sure the FETCH value was >1000 when I set the max_row_buffer > 1000
image

**Review by zzzeek — CHANGES_REQUESTED** [review]
OK, we're assuming here a relatively low buffer growth, like if they set it to 100000, it would just jump but I guess that's not that big a deal as this whole feature is a little overkill in the first place.    Can you please add a test right at https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_resultset.py#L1959, you can just copy that method to make another one that sets max_row_buffer to a value higher than 1000.

**Comment by sumau** [comment]
ok will have a look this weekend since haven't used nose before

**Comment by zzzeek** [comment]
> ok will have a look this weekend since haven't used nose before

we don't use nose, the tests are run with py.test and/or tox.   see README.unittests.txt

**Comment by sumau** [comment]
Done! Hadn't used pytest before but documentation for running tests was very clear.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 66841f56e967c784f7078a787cec5129462006c8 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 66841f56e967c784f7078a787cec5129462006c8: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1550

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1550 has been **merged**. Congratulations! :)

**Pull request closed without merging**
