### PR TITLE
Add missing parameter to docstring

### PR DESCRIPTION
**Pull request by agamrafaeli**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get this PR into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Change has been squashed to Gerrit review: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1041

**Comment by zzzeek** [comment]
now ideally it wouldn't run the whole test suite for a simple doc change.....but not easy to detect

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1041 has been **merged**. Congratulations! :)

**Pull request closed without merging**
