### PR TITLE
Fix DATETIMEOFFSET formatting to preserve fractional seconds.

### LINKED ISSUE #5045: mssql pyodbc DATETIMEOFFSET - fractional seconds not persisted
A recent change to DATETIMEOFFSET for mssql+pyodbc appears to have caused fractions of seconds not to be persisted:

https://github.com/sqlalchemy/sqlalchemy/issues/4983
https://github.com/sqlalchemy/sqlalchemy/blob/d6d61ffe4ce207428b24b38431b75af5f5df1cf4/lib/sqlalchemy/dialects/mssql/pyodbc.py#L238

It looks like the call the strftime is disregarding any fractional part.

### PR DESCRIPTION
**Pull request by gordthompson**
Fixes: #5045

### Description
pyodbc requires that T-SQL DATETIMEOFFSET values be passed as strings, and we were formatting `datetime` objects as strings without the fractional seconds.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 91b10538315adbbb9e27f5340cd91559dcd0973b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 91b10538315adbbb9e27f5340cd91559dcd0973b: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1622

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

can we get a doc/build/unreleased_13/5045.rst file for this?  Also the paragraph from the 5045.rst file becomes the text of the changelog, replacing the pull request template text.

**Comment by gordthompson** [comment]
I have added the changelog file. Is there anything else I can do?

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 85e598cb31a4f1748790aa3ebb4c96f4c362871f of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 85e598cb31a4f1748790aa3ebb4c96f4c362871f added to existing Gerrit review https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1622

**Comment by gordthompson** [comment]
https://jenkins.sqlalchemy.org/job/pep8/1805/console

says that the pep8 test failed because

> ./test/orm/test_relationships.py:434:1: RST218 Literal block expected; none found.

"As Git is my witness", I was nowhere near the scene of the crime. ;)

**Comment by zzzeek** [comment]
yes I know, what happens is new releases of flake8-rst whatever come out and suddenly find new issues.   the latest master / 1.3 branch fixes that failure.

**Comment by gordthompson** [comment]
My branch now includes 915983c so perhaps we can try again.

**Comment by zzzeek** [comment]
hmmmm  do you know how to rebase from master?  that would have saved you a lot of commits here, I'm assuming you merged ?

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 99dc7b23f69b7b068795a02d20b88bf352c7dcd7 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 99dc7b23f69b7b068795a02d20b88bf352c7dcd7 added to existing Gerrit review https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1622

**Comment by zzzeek** [comment]
there are unfortunately more test failures in master that sneaked in so this likely will still not pass

**Comment by gordthompson** [comment]
> do you know how to rebase from master?

I did start out by choosing VCS > Git > Rebase... in PyCharm, but after crunching for a bit it popped up a dialog warning about unmerged commits and "**strongly suggest**[ing]" (emphasis theirs) that it should do a Merge instead. I had the option to forge ahead with the Rebase but I didn't really know why PyCharm was complaining (I sometimes find PyCharm a bit convoluted when it comes to Git) so I played it safe and did as I was told.

**Comment by gordthompson** [comment]
> more test failures in master that sneaked in so this likely will still not pass

Your prediction was correct. Ping me when master has been updated and you'd like me to tweak this PR again. (Maybe I'll try doing a rebase from Git Bash next time.)

**Comment by zzzeek** [comment]
> > do you know how to rebase from master?
> 
> I did start out by choosing VCS > Git > Rebase... in PyCharm, but after crunching for a bit it popped up a dialog warning about unmerged commits and "**strongly suggest**[ing]" (emphasis theirs) that it should do a Merge instead. I had the option to forge ahead with the Rebase but I didn't really know why PyCharm was complaining (I sometimes find PyCharm a bit convoluted when it comes to Git) so I played it safe and did as I was told.

how interesting!

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1622 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1643 has been **merged**. Congratulations! :)

**Pull request closed without merging**
