### PR TITLE
Docs: simplify language use for "Working with Transactions and the DBAPI"

### PR DESCRIPTION
**Pull request by lonkeknol**
### Description
This is my first pull request to sqlalchemy. It changes the writing style of two paragraphs in the unified tutorial [here](https://docs.sqlalchemy.org/en/20/tutorial/dbapi_transactions.html#working-with-transactions-and-the-dbapi). My goals were to.
1. Make them easier to read
2. Not change the meaning of the text.
3. Get feedback on whether this type of contribution is considered useful for sqlalchemy.

If this is a useful type of contribution, it might be good to discuss some general guidelines for me to adhere to as I continue. For instance:
- Prefer using present simple tense
- Remove superfluous words where possible
- Keep the pull requests to one or two h2 sections at a time, to make the review easier

### Checklist
This pull request is:

- [x] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

I'm curious to hear what you all think. **Have a nice day!**

### CODE REVIEW

**Review by zzzeek — APPROVED** [review]
great changes, thanks

**Comment by zzzeek** [comment]
>    Prefer using present simple tense

should be good

>    Remove superfluous words where possible

yah definitely.  this was a lot of docs to write, they just sneak in there

>    Keep the pull requests to one or two h2 sections at a time, to make the review easier

very much so, great idea thanks

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 3179690e6a5b47de99a4486a7a15cffbfacd380b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 3179690e6a5b47de99a4486a7a15cffbfacd380b: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5406

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5406 has been **merged**. Congratulations! :)

**Pull request closed without merging**
