### PR TITLE
fix versioned-history example

### PR DESCRIPTION
**Pull request by martell**
Code to show issue as described in #9220 

run `python3 -m unittest examples/versioned_history/test_versioning.py`

@zzzeek I hope you can help, this is broken since https://github.com/sqlalchemy/sqlalchemy/commit/5ec5b0a6c7b618bba7926e21f77be9557973860f

### CODE REVIEW

**Comment by zzzeek** [comment]
seems fine, we can merge

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 38eac579998bab57c319b92ee23a756707e1ac06 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 38eac579998bab57c319b92ee23a756707e1ac06: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4415

**Comment by zzzeek** [comment]
is there a reason this is in draft still?

**Comment by zzzeek** [comment]
closing this, the change to make the test work as written I'll share on the issue, however, that's not how I want to do it

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

i did a full rework of the example in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4422

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4415

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4415 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
