### PR TITLE
Test for _ORMJoin and fix issue

### PR DESCRIPTION
**Pull request by kataev**
Motivated volunteer here, tests and fix for #4713

### CODE REVIEW

**Comment by zzzeek** [comment]
wow you're amazing!    thanks so much for this!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision ac8870614947259320b5d000a59fadb8c2328a04 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change ac8870614947259320b5d000a59fadb8c2328a04: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1332

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1332 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1335 has been **merged**. Congratulations! :)

**Pull request closed without merging**
