### PR TITLE
Add py3.8, py3.9 token to setup.py

### LINKED ISSUE #5113: add py3.8, py3.9 token to setup.py
https://github.com/sqlalchemy/sqlalchemy/blob/master/setup.py#L161-L164

### PR DESCRIPTION
**Pull request by gordthompson**
Fixes: #5113

### Description
Add py3.8 and py3.9 tokens to setup.py

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
What do you think if we just did "Python :: 3"   ?  Python 3.4 is our lowest supported version and is EOL soon.   note this great point made on twitter: https://twitter.com/leandropls/status/1220362758539087873  "I don't understand Python :: 3 as meaning all Python 3 versions, more like "current Python 3". Otherwise, what would Python :: 2 mean? Python 2.0?"   they have a point.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 5ae662f1ec0d89a16a03fe60d6f12712d0d21398 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5ae662f1ec0d89a16a03fe60d6f12712d0d21398: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1688

**Comment by cclauss** [comment]
3.4 is ___already___ EOL.
https://devguide.python.org/#status-of-python-branches
https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/1688

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1688 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/1689

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1689 has been **merged**. Congratulations! :)

**Pull request closed without merging**
