### PR TITLE
Make discriminator column used by ConcreteBase configurable

### PR DESCRIPTION
**Pull request by Jesse-Bakker**
### Description
Allow using `_concrete_discriminator_name` attribute on `ConcreteBase` to configure the name of the discriminator column used when querying polymorphically.

I am not familiar with the codebase, so I'm not sure how to test this.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [x] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
nice.  do you have the appetite to try to make a test?  no biggie I can just add one.

**Comment by Jesse-Bakker** [comment]
I made a test that simply asserts the compiled SQL

**Comment by zzzeek** [comment]
taht's all we need!  thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 2f5ffa3a15c8d309ee1551d5ea2a47d0a67376c6 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 2f5ffa3a15c8d309ee1551d5ea2a47d0a67376c6: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151

**Comment by zzzeek** [comment]
there's been some quick fixes for the test suite in master this morning so if the tests fail here don't panic

**Review by sqla-tester — COMMENTED** [review]
Hi, this is **sqla-tester** and I see you've pinged me for review. However, user **Jesse-Bakker** is not authorized to initiate CI jobs.  Please wait for a project member to do this!

**Comment by zzzeek** [comment]
oh thanks, i was going to get to it.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 95192766a27cc47d5c97173313d9f91b151c9582 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 95192766a27cc47d5c97173313d9f91b151c9582 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151

**Comment by Jesse-Bakker** [comment]
Keep forgetting to run flake8 before I push :sweat_smile:

**Comment by zzzeek** [comment]
> Keep forgetting to run flake8 before I push sweat_smile

we use pre-commit to ensure everything is formatted.   if you install pre-commit in the working directory it will run black + zimports + flake8.

**Comment by Jesse-Bakker** [comment]
Should've read the contributor guide better. Installed it now, ran it and everything should be alright now

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 5e7429f3531e2e22fffe996c9760905578d16ef9 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 5e7429f3531e2e22fffe996c9760905578d16ef9 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2151 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2156

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2156 has been **merged**. Congratulations! :)

**Pull request closed without merging**
