### PR TITLE
Docs: simplify language in getting a connection & committing changes

### PR DESCRIPTION
**Pull request by lonkeknol**
### Description
Simplifies language use in [Getting a Connection](https://docs.sqlalchemy.org/en/20/tutorial/dbapi_transactions.html#getting-a-connection) and [Committing Changes](https://docs.sqlalchemy.org/en/20/tutorial/dbapi_transactions.html#committing-changes)

### Checklist
This pull request is:

- [x] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by CaselIT — APPROVED** [review]
thanks

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision d706e69fb6058d3483fce98cfacbbf36ca12d78e of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change d706e69fb6058d3483fce98cfacbbf36ca12d78e: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5407

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5407 has been **merged**. Congratulations! :)

**Comment by zzzeek** [comment]
thanks! these are good.    for docs this is totally fine either way but are you using GPT for these or is it just manual?  (I have used chatGPT to reword paragraphs before)

**Comment by lonkeknol** [comment]
This is manual. To be honest, I want to understand sqlalchemy better, so rewriting is also a great way for me to absorb what is written, instead of skimming over it.

**Comment by zzzeek** [comment]
that's terrific!   great work!

**Pull request closed without merging**
