### PR TITLE
Create a compiler hook to pick up custom objects in expressions

### PR DESCRIPTION
**Pull request by lelit**
This simply applies what has been suggested by Mike in issue #8884, and seems to work. I guess more work is needed, for example mentioning and/or documenting the new __sa_type_engine__ hook.

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 6e95e08a30597d3735ab38f2f1a2ccabd968852c of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by zzzeek** [comment]
it's good enough for now :)

**Comment by sqla-tester** [comment]
New Gerrit review created for change 6e95e08a30597d3735ab38f2f1a2ccabd968852c: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4248

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks for the review!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4248

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4248 has been **merged**. Congratulations! :)

**Pull request closed without merging**
