### PR TITLE
Add support for Python 3.13

### PR DESCRIPTION
**Pull request by hugovk**
### Description

Python 3.13 is due out today! 🚀 

https://peps.python.org/pep-0719/

It's already tested here, let's add the classifier.

### Checklist

This pull request is:

- [x] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by zzzeek — APPROVED** [review]

**Comment by CaselIT** [comment]
In theory wheels for 3.13 should be created in the next release. In practice we will see I guess :)

**Comment by henryiii** [comment]
Nice! Just noticed sqlalchemy is one of only 21 projects in the top 360 python packages to be shipping 3.12 wheels but not 3.13.

**Comment by CaselIT** [comment]
As written above the next release will ship wheels. It's generally poor form to make pressure to mantainers, so please be patient...

**Comment by henryiii** [comment]
Sorry, I meant I was happy to see it was already handled and would be coming out soon(ish).

**Pull request merged**
