### PR TITLE
8152: add documentation for postgresql dialect time and timestamp types

### PR DESCRIPTION
**Pull request by DanielHall977**
add documentation for postgresql dialect time and timestamp types

This pull request is:

- [ X] A documentation / typographical error fix
	- Good to go, no issue or tests are needed

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
this looks great.  it might need you to run black on it though

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 2b76fe080babd72f8e5615b34cb544abbc446a28 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 2b76fe080babd72f8e5615b34cb544abbc446a28: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3955

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3955 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3956 has been **merged**. Congratulations! :)

**Pull request closed without merging**
