### PR TITLE
Add Range.__contains__

### LINKED ISSUE #12093: Implement Range.__contains__
### Describe the use case

I'm upgrading from SQLAlchemy 1.4 where the psycopg2 range types are used, and `Range.__contains__` is implemented for those.

### Databases / Backends / Drivers targeted

PostgreSQL dialect

### Example Use

the psycopg2 types implement it, but if selecting a column that is e.g. `INT4RANGE` then the sqlalchemy `Range` type is returned:

```python
>>> range1 = conn.scalar(select(func.int4range(1, 10)))
>>> range1
NumericRange(1, 10, '[)')
>>> 3 in range1
True
>>> 12 in range1
False

>>> range2 = conn.scalar(select(type_coerce(func.int4range(1, 10), INT4RANGE)))
>>> range2
Range(lower=1, upper=10, bounds='[)', empty=False)
>>> 3 in range2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'Range' is not iterable
```

### Additional context

I'll open a PR

### PR DESCRIPTION
**Pull request by RazerM**
### Description
Fixes #12093

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by lelit** [comment]
Seems a sensible thing, thank you.

**Comment by CaselIT** [comment]
makes sense too. Could you add a changelog note here https://github.com/sqlalchemy/sqlalchemy/tree/main/doc/build/changelog/unreleased_20? id is the issue

**Comment by CaselIT** [comment]
i'll do that. thanks for the PR

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 3f900e96b95c6dbd20ee6f5aa3f49dd6124ffba9 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 3f900e96b95c6dbd20ee6f5aa3f49dd6124ffba9: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5596

**Comment by lelit** [comment]
For the sake of history, we discussed this long ago: https://groups.google.com/g/sqlalchemy/c/MC8EJrVMmQs/m/-35KsvOrAgAJ. It surfaced my memory this morning...

**Comment by CaselIT** [comment]
good memory! @zzzeek what do you think?

**Comment by zzzeek** [comment]
OK erase that previous message, that's not how `__contains__` works, it's not called in the reverse direction like that.   I can even add a broken ``__contains__`` to `ColumnElement` and basic tests still pass at least.

still I think the discomfort with `__contains__` was based on how it seems to imply SQL IN but does not actually achieve that.

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5596 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5597 has been **merged**. Congratulations! :)

**Pull request closed without merging**
