### PR TITLE
Bump Sphinx

### LINKED ISSUE #5790: [docs.sqlalchemy.org] Search keeps crashing my browser
When I use the search functionality on docs.sqlalchemy.org it typically starts displaying a huge number of results which in only a couple of seconds results in using GBs of RAM, which then results in my browser crashing when the system runs out of memory.

I guess an obvious solution would be to implement pagination, rather than loading unlimited amount of results in the page.

Firefox on Linux.

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Hopefully fixes #5790

### CODE REVIEW

**Comment by zzzeek** [comment]
im tying to run sphinx 1.5 on my server and getting very strange results, will have to spend some time understanding what's going on.  nonetheless the server upgrades sphinx automatically so it was already on 1.5 (and failing).

**Comment by Dreamsorcerer** [comment]
OK, I guess this PR isn't needed then.

**Comment by zzzeek** [comment]
we can still merge it i just need to get the build to work on the live server, it is doing something very strange at the moment.

**Comment by zzzeek** [comment]
we are blocked by https://github.com/sphinx-doc/sphinx/issues/8894

**Comment by zzzeek** [comment]
thanks for the PR!

**Pull request merged**
