### PR TITLE
Remove redundant assignment in .../engine/create.py

### PR DESCRIPTION
**Pull request by pedrocunial**
### Description

Remove a redundant assignment in the engine creation file.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
thanks!  will run this through CI

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 4a0e6206f0ae5ff5350ecaa6f998bc3dc0c26cdd of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 4a0e6206f0ae5ff5350ecaa6f998bc3dc0c26cdd: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1551

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

openstack-recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

**Pull request closed without merging**
