### PR TITLE
Add opsclass to exclusion constraint

### LINKED ISSUE #5604: Are operator classes supported for Postgresql exclusions constraints?
I want to create a table with an exclusion constraint where the constraint is for a column of type `CIDR` and the operator is `&&`.
Hence i need to use the `inet_ops` operator class
see: https://dba.stackexchange.com/questions/205773/how-to-find-out-what-operator-class-and-access-method-should-be-used-for-an-excl

The only solution talking about something like that is the following:
https://stackoverflow.com/questions/34646454/error-data-type-inet-has-no-default-operator-class-for-access-method-gist

However, i am getting an Exception when trying to run the example code found there:

```
Traceback (most recent call last):
  File "models.py", line 38, in <module>
    class IPv4PrefixTable(Base):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/ext/declarative/api.py", line 75, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 160, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 190, in __init__
    self._setup_table()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 538, in _setup_table
    **table_kw
  File "<string>", line 2, in __new__
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 506, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 501, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 600, in _init
    self._init_items(*args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 117, in _init_items
    spwd(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 456, in _set_parent_with_dispatch
    self._set_parent(parent)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2903, in _set_parent
    ColumnCollectionMixin._set_parent(self, table)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2860, in _set_parent
    for col in self._col_expressions(table):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2856, in _col_expressions
    for col in self._pending_colargs
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2856, in <listcomp>
    for col in self._pending_colargs
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/_collections.py", line 194, in __getitem__
    return self._data[key]
KeyError: 'prefix inet_ops'
```

It makes sense, as i am passing the `inet_ops` as part of the column name, and such a column does not exist.

Is there any solution for this?

**Versions**
 - OS: Mac 10.15.6
 - Python: 3.7
 - SQLAlchemy: 1.3.11
 - Database: PostgreSQL 11
 - DBAPI:

### PR DESCRIPTION
**Pull request by alonme**
Fix #5604 - add operation classes support to exclusion constraints.

### Description
Add an ops kw param to ExcludeConstraint, that behaves similarly to postgres-ops in an Index.

### Checklist
This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by alonme** [comment]
Hi,
Adding a simple implementation of the feature, including tests and some docs.

I feel like `ops`  can be changed to something like `opclass` so we are line with the PG docs, however i left it to be in sync with Index.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision f8613e100792fc0bb3cf300ec6aebc78ecdf0361 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change f8613e100792fc0bb3cf300ec6aebc78ecdf0361: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2364

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2364

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2364 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

i need to doa separate patch to correct the versionadded version i just noticed is wrong

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2368

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2368 has been **merged**. Congratulations! :)

**Pull request closed without merging**
