### PR TITLE
Type annotate postgresql dml

### PR DESCRIPTION
**Pull request by mehdigmira**
### Description
The goal is to annotate postgresql specific apis that are under postgresql/dml.py file.
I've looked around to see what types are used for similar apis, hope I got it right :)

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
pretty good.  you're going to want to install and run [pre-commit](https://pre-commit.com/) to get all of our pep8/import conventions in place.    Also any chance you can drop these annotations into the sqlite/ddl.py file also?  it should be extrmely similar.

note also we are going **very** slow right now getting new annotations in, though this one looks pretty small so maybe i can fast track it

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 5bc35641d8818ba2e800221aa057bf4354dbbe9b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5bc35641d8818ba2e800221aa057bf4354dbbe9b: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736

**Comment by mehdigmira** [comment]
> pretty good. you're going to want to install and run [pre-commit](https://pre-commit.com/) to get all of our pep8/import conventions in place. Also any chance you can drop these annotations into the sqlite/ddl.py file also? it should be extrmely similar.
> 
> note also we are going **very** slow right now getting new annotations in, though this one looks pretty small so maybe i can fast track it

Ok, I will update the PR.
What's the reason for slowing down the integration of new annotations ?

**Comment by zzzeek** [comment]
> > note also we are going **very** slow right now getting new annotations in, though this one looks pretty small so maybe i can fast track it
> 
> Ok, I will update the PR. What's the reason for slowing down the integration of new annotations ?

mostly fatigue?

**Comment by mehdigmira** [comment]
- Ran pre-commit on files
- Handled sqlite as well
- Cleaned up a import error that caused the pipeline to fail

If it has your approval @zzzeek and pipeline passes, we'll just have to cleanup commit history

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision c7718b6273319a534b1c2aac2f70e16201797bf9 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Failed to create a gerrit review, git squash against branch 'main' failed

**Comment by zzzeek** [comment]
dont worry about squashing, that happens automatically in the process we use

**Comment by zzzeek** [comment]
oh but I *do* need you to rebase against main please

**Comment by mehdigmira** [comment]
all good now ?

**Review by sqla-tester — COMMENTED** [review]
Hi, this is **sqla-tester** and I see you've pinged me for review. However, user **mehdigmira** is not authorized to initiate CI jobs.  Please wait for a project member to do this!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 0562f093974520b162de31e8473a4d4d6656d529 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 0562f093974520b162de31e8473a4d4d6656d529 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

OK next trick.  Can we put some tests in test/typing/plain_files/dialects ?

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736

**Review by zzzeek — CHANGES_REQUESTED** [review]
I think it's good but we should put some tests in, now that we have a newly refactored typing test suite:

test/typing/plain_files/dialects/
test/typing/plain_files/dialects/postgresql seems to be there, so I guess we could build out a subdir for sqlite also

**Comment by zzzeek** [comment]
note that "tests" here just means some python files that will be run on mypy.  they are *not* run in the normal python intepreter so do not have to make sense.     optionally can include reveal_type() assertions, look at some other files in there to see, they are like this:

```py

r3 = connection.execute(stmt)

# EXPECTED_TYPE: Result[Tuple[int]]
reveal_type(r3)

```

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Looks ok. There is also mysql that's somewhat the same.
Should it be typed too?

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736

**Comment by zzzeek** [comment]
sure, everything should be typed :)    wasn't going to ask the sumitter to type all of sqlalchemy.dialects :)

**Comment by CaselIT** [comment]
> sure, everything should be typed :) wasn't going to ask the sumitter to type all of sqlalchemy.dialects :)

well we got sqlite in there :)

Let me finish this

**Comment by CaselIT** [comment]
pushed updated version on gerrit.

@zzzeek is a changelog needed?

**Comment by zzzeek** [comment]
probably not

**Comment by CaselIT** [comment]
then it should be good to go

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

nope mypy is not happy

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

should now be ok

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736

**Comment by mehdigmira** [comment]
I see @CaselIT overtook the PR in gerrit. Nothing left to do from my side, right ?

**Comment by CaselIT** [comment]
I took the liberty of updating also mysql.
Nope nothing left on your side, thanks for the effort!

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4736 has been **merged**. Congratulations! :)

**Pull request closed without merging**
