### PR TITLE
refactor: Add type hints to `lib.sqlalchemy.ext.compiler`

### PR DESCRIPTION
**Pull request by kkirsche**
### Description
This change provides type hints for the `compiles` decorator located in `lib.sqlalchemy.ext.compiler`. The intent is to ensure that examples such as ["UTC timestamp" function](https://docs.sqlalchemy.org/en/20/core/compiler.html#utc-timestamp-function) work with `mypy`. 

This change uses a `TypeVar` bound to `Callable[..., Any]` as I'm not sure if the signature represented in the example always applies. If it does, we can update this bind to be more specific. I would need help defining how, though, as I don't know what the correct base class is for the `element` or `compiler`.

If we also chose to type `kw` (assuming that's well defined), we can use `typing_extensions.Unpack` as described in the [typing documentation](https://docs.python.org/3/library/typing.html#typing.Unpack).

Where my use of `typing` imports is specific to the python version support of SQLAlchemy, I have noted this with `TODO` comments so they can easily be located and changed in the future.

Finally, I left a few functions in this file untyped because I wasn't sure what their types were. These seem to be the same signature I mentioned in my `TypeVar` paragraph above, so if you have any feedback about this I'm happy to incorporate it.

X-Ref: #6810 

### Checklist

This pull request is:

- [X] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by kkirsche** [comment]
I'm not sure what the correct fix is for the linting error given that the error is due to the TODO comments. I'll hold off on further changes until I receive feedback about how you would like to address that. For example, remove the comments, put them above or below, add `noqa` directives, etc.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 3a7719ff96c754af2575c5385c8d4fa4d5492113 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 3a7719ff96c754af2575c5385c8d4fa4d5492113: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5512

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5512 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5517 has been **merged**. Congratulations! :)

**Comment by kkirsche** [comment]
Thank you for your time and help preparing this! Have a wonderful week 🙂

**Pull request closed without merging**
