### PR TITLE
added fire sequence method for mssql dialect - issue 4627

### PR DESCRIPTION
**Pull request by Lakshay-Awasthi**
Sequence not getting executed for mssql dialect
### Checklist

This pull request is:

- [ x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<4627>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [x ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by Lakshay-Awasthi** [comment]
Fixes: #4627

**Comment by Lakshay-Awasthi** [comment]
Fixes: #4627

**Comment by zzzeek** [comment]
so this needs elements that you can see in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/724/.    when the "supports_sequences" flag is set, that adds test support.   But I think to do this we also have to fully remove the deprecated bits at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mssql/base.py#L1885 .    these changes should be made against master, but in order for them to merge I have to create the 1.4 branch which I haven't done yet (have been travelling).   but the patch can be tested, at least (also requires that the deprecated tests be removed from test/dialect/mssql/test_compiler.py).

**Comment by Lakshay-Awasthi** [comment]
Dear @Mike, to add these changes what all is required, as I am not able to use the sequence feature for my project

**Comment by zzzeek** [comment]
> Dear @mike, to add these changes what all is required, as I am not able to use the sequence feature for my project

to invoke the sequence you can say "session.scalar("select next value for my_seq")", so I would suggest trying to work with that in the meantime if direct invocation is all you need.

The beginning of the correct patch can be seen in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/724/1/lib/sqlalchemy/dialects/mssql/base.py.   That's the code, then basically getting the tests to pass which likely includes removing all the "IDENTITY" logic that interacts with Sequences.

**Comment by zzzeek** [comment]
closing this for now, as we have to work with the test failures in  https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/724/ to make this happen, which likely means first removing all the deprecated SQL server usages of Sequence.   unfortunately not simple

**Pull request closed without merging**
