### PR TITLE
Add issue template, other github files

### PR DESCRIPTION
**Pull request by CaselIT**
You can test it at https://github.com/CaselIT/sqlalchemy/issues/new/choose

### CODE REVIEW

**Comment by CaselIT** [comment]
I was thinking that maybe it's not the best it the issue adds a label on creation, since it's harder to see the new ones?
Or maybe it could have also a new label, something like triage?

**Comment by zzzeek** [comment]
yeah "requires triage" is great

**Comment by CaselIT** [comment]
updated the label and added to the project

**Comment by zzzeek** [comment]
this is SO GOOD.   Just needs to be in master right?

**Comment by CaselIT** [comment]
yes

**Pull request merged**
