### PR TITLE
Fixes: #6915

### PR DESCRIPTION
**Pull request by tsimafeip**
### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted. - Issue #6915
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks,

I looked for the `=\[\]` regexp in lib and it seems we have another case:
https://github.com/sqlalchemy/sqlalchemy/blob/5c4a74fc13ca28983706a76ab02ffe09d89d1dbf/lib/sqlalchemy/engine/url.py#L658

could you also fix that one?

**Comment by CaselIT** [comment]
Found also this one using ` =\{\}` regexp

https://github.com/sqlalchemy/sqlalchemy/blob/5c4a74fc13ca28983706a76ab02ffe09d89d1dbf/lib/sqlalchemy/util/compat.py#L366-L380

**Comment by zzzeek** [comment]
> Found also this one using ` =\{\}` regexp
> 
> https://github.com/sqlalchemy/sqlalchemy/blob/5c4a74fc13ca28983706a76ab02ffe09d89d1dbf/lib/sqlalchemy/util/compat.py#L366-L380

this is straight from stdlib:

https://github.com/python/cpython/blob/main/Lib/inspect.py#L1372

how come they are doing it?

**Comment by CaselIT** [comment]
looking at the code it's safe, since they are not returned and nothing writes on the dict in the function.

(well I guess if one messes with the inspected default args)

**Comment by tsimafeip** [comment]
Yep, it is safe in the code, but my linter warned me on method override that the signature does not match the base. 
Anyway, it is worth fixing. 

Feel free to add same-style fixes to the PR.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 6ec484d3d14b7dd7053d10a5d550bd74eb524c8b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 6ec484d3d14b7dd7053d10a5d550bd74eb524c8b: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3022

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

I've updated also the translate_connect_args and inspect_formatargspec even if they were safe just for consistency

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3022

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3022

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

done and done

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3022

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3022 has been **merged**. Congratulations! :)

**Pull request closed without merging**
