### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by hugovk**
### Description

Python 3.10 was released last week.

Test on Python 3.10 and add the Trove classifier.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

^ Which checklist option should I use?

Should I do something to trigger/test all the workflows?

### CODE REVIEW

**Comment by CaselIT** [comment]
The test run is here going on here https://github.com/CaselIT/sqlalchemy/actions/runs/1330013896

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision d818289e4266a3f3f7a632e9650a7e86c6115d14 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change d818289e4266a3f3f7a632e9650a7e86c6115d14: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3162

**Comment by hugovk** [comment]
Has PyPy 3.8 been released yet? PyPy 3.7 is the latest one at https://www.pypy.org/download.html.

Or there is a release candidate: https://mail.python.org/pipermail/pypy-dev/2021-September/016214.html

But at least I've only seen PyPy 3.6 and 3.7 on GHA lately.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 5df7ff0e0d309301a877314e620fadb6f3f570cb of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 5df7ff0e0d309301a877314e620fadb6f3f570cb added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3162

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3162 has been **merged**. Congratulations! :)

**Pull request closed without merging**
