### PR TITLE
Bug fix for code example: append to addresses instead of User object

### PR DESCRIPTION
**Pull request by EdwardBetts**
Correct a mistake in a code example.

### CODE REVIEW

**Review by jvanasco — APPROVED** [review]
LGTM

**Comment by CaselIT** [comment]
this needs also a 1_3. will put on gerrit

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 18fef6af669762a11c7f4da5de1dd42b3bbc2a55 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 18fef6af669762a11c7f4da5de1dd42b3bbc2a55: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2708

**Comment by zzzeek** [comment]
OK I can just merge + backport this withotu going through the whole gerrit thing

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

merged independently

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2708

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2708 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

this was merged independently

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2709

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2709 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request merged**
