### PR TITLE
Update paths in CHANGES

### PR DESCRIPTION
**Pull request by stigok**
### Description
Outdated path to in-repo changelog. Removed whitespace as well.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by jvanasco** [comment]
LGTM. My only concern is if this should point to the .rst file

Do @CaselIT or @zzzeek have an opinion?  I can pull this through gerrit if you're both ok with this as-is.

**Comment by stigok** [comment]
I agree that might be the case. I just found the index.rst file to unhelpful :)

**Review by CaselIT — APPROVED** [review]

**Comment by zzzeek** [comment]
I'm still -1 on a github-only link here.   Please change the text to:

```
For an index of all changlogs, please see:

* On the web - http://www.sqlalchemy.org/docs/latest/changelog/

* In the source tree - /doc/build/changelog/

* In the released distribution file:   /doc/changelog/index.html


```

there's no point in having the whole doc/.html build in every distribution if we assume people are not browsing the distribution file.   if nobody looks inside the .tar.gz anymore and pip install has made it obsolete, then we should remove the whole doc/index.html build from releases.

**Comment by stigok** [comment]
Will you squash when merging, or should I squash myself beforehand?

**Comment by zzzeek** [comment]
ill pull this through gerrit just so it's automatic

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision f69e6adbe85997c88cb1c6e6c564cefdbc1c874a of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change f69e6adbe85997c88cb1c6e6c564cefdbc1c874a: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2215

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1 Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2215

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2215 has been **merged**. Congratulations! :)

**Comment by stigok** [comment]
Thanks :+1:

**Pull request closed without merging**
