### PR TITLE
Fix docs typo: subuqery -> subquery

### LINKED ISSUE #5839: 'subuqery' typo (3 instances) in docs -> should be 'subquery'
Ran across `Subuqery IN` here https://docs.sqlalchemy.org/en/14/core/operators.html#subuqery-in, then realized it was a typo (should be 'Subquery'). Searching the codebase, I found 2 more instances: 

https://github.com/sqlalchemy/sqlalchemy/search?q=subuqery

image

### PR DESCRIPTION
**Pull request by etmoore**
### Description
Fixes #5839
(sorry, realized just now that an issue wasn't required)

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision b6f6af929fab4dab771565f6373b0275acbca793 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change b6f6af929fab4dab771565f6373b0275acbca793: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2473

**Comment by CaselIT** [comment]
Thanks!

**Comment by sqla-tester** [comment]
**Gord Thompson** (gordthompson) wrote:

Code-Review+1 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2473

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2473

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2473

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2473 has been **merged**. Congratulations! :)

**Pull request closed without merging**
