### PR TITLE
Fixes: #6583

### PR DESCRIPTION
**Pull request by yicheng47**
### Description
1. Implement async_scoped_session to support await keyword for AsyncSession's method

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [x] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by jason3gb** [comment]
It's a little harder than I thought previously. I try my best to implement it and add a basic test. Please give some advice on whether you think this "draft" version is on the right track. Thanks.

**Comment by jason3gb** [comment]
@zzzeek Hi, sorry to bother again, do you have time to take a look at this pr?

**Comment by zzzeek** [comment]
hi sorry was not following this, we can put it through gerrit

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision e82e71a3597b15ab6a464df708a9a1e3984f8fe2 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change e82e71a3597b15ab6a464df708a9a1e3984f8fe2: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

**Review by sqla-tester — COMMENTED** [review]
Hi, this is **sqla-tester** and I see you've pinged me for review. However, user **jason3gb** is not authorized to initiate CI jobs.  Please wait for a project member to do this!

**Comment by jason3gb** [comment]
@zzzeek Forget to setup the pre-commit hooks, fixed the pep8 check.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 8bb95627717e880c8ef02ac6d21061a9636c4e09 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 8bb95627717e880c8ef02ac6d21061a9636c4e09 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

looks good.   this needs docs to be set up in asyncio.rst, additionally we might need to add an "inherited-members" directive to the existing scoped_session class so that the moved method shows up.   also needs a changelog file.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

**Comment by zzzeek** [comment]
very nice!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 0e8ef87dc824dcd83dca01641441afc453c8e07a of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 0e8ef87dc824dcd83dca01641441afc453c8e07a added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

**Comment by jason3gb** [comment]
> very nice!

Thanks, tried my best, not write in English officially for a while :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

**Comment by jason3gb** [comment]
> **mike bayer** (zzzeek) wrote:
> 
> recheck
> 
> View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

@zzzeek Is the error caused by the CI process or the newly added code ? I'm a little confused with the console output.

**Comment by zzzeek** [comment]
CI failed for network reasons, it's a problem we haven't solved.   you're done, this is great, I just went over it a bit, should be able to merge today.  thanks!

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

great job thanks very much!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2870 has been **merged**. Congratulations! :)

**Pull request closed without merging**
