### PR TITLE
Add github action workflow to run tests on master and on pr to master

### PR DESCRIPTION
**Pull request by CaselIT**
Trying the pr to check if it works right away

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 5601447b74f28e5acb17509146762f543f3d3f13 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5601447b74f28e5acb17509146762f543f3d3f13: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821

**Comment by CaselIT** [comment]
I originally opened a pr for this because I thought it would start the action. But I seems that it already need to be in the master branch for this to work.
From the documentation
> When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.

**Comment by zzzeek** [comment]
looks fine?  I don't really know.  wouldnt you need to add container runs for all the databases that are not sqlite ?

**Comment by CaselIT** [comment]
I can add some documentation to the file so it would be easier to modify by others without needing to read all the documentation. Would that help?

**Comment by zzzeek** [comment]
if it's easy to add clarification then sure!

**Comment by CaselIT** [comment]
I've added some comments on what each section does.
Hopefully it's a bit easier to understand.

**Comment by CaselIT** [comment]
Maybe I should make the workflow run even for pushes in branches named rel*

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 859463494c9151910aaef24327a4f92d8f1ce414 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 859463494c9151910aaef24327a4f92d8f1ce414 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision afbb8567525f3841554d3ba599ef4d713c78e647 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset afbb8567525f3841554d3ba599ef4d713c78e647 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Code-Review+1

I think this is ready to be merged. I've added the changed we talked about yesterday:
- only run the full matrix on push to master and rel_
- run a single job on linux in the pr

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821

**Comment by sqla-tester** [comment]
**Gord Thompson** (gordthompson) wrote:

Code-Review+1

I know nada about GitHub Actions, but what I see here seems to make sense.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

Merging this so that we can do things with it, but like Gord I don't know much about what's happening here :)   it's all in .github so that's good.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1821 has been **merged**. Congratulations! :)

**Comment by CaselIT** [comment]
I think we could also backport it to rel_13

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Code-Review+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1856

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1856

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1856

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1856 has been **merged**. Congratulations! :)

**Pull request closed without merging**
