### PR TITLE
Add Non linear CTE support

### PR DESCRIPTION
**Pull request by Morikko**
Fixes: #7259

Allow:
```sql
WITH RECURSIVE nodes(x) AS (
   SELECT 59
   UNION
   SELECT aa FROM edge JOIN nodes ON bb=x
   UNION
   SELECT bb FROM edge JOIN nodes ON aa=x
)
SELECT x FROM nodes;
```

Based on @zzzeek suggestion: https://github.com/sqlalchemy/sqlalchemy/pull/7133#issuecomment-933882348

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision f6c6e49c8b36fd7b492f15ccab6fdb52c9a07c9d of this pull request into gerrit so we can run tests and reviews and stuff

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision f6c6e49c8b36fd7b492f15ccab6fdb52c9a07c9d of this pull request into gerrit so we can run tests and reviews and stuff

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 1b3ff4fa433594d7621f9e9059e5afd82849b9bc of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 1b3ff4fa433594d7621f9e9059e5afd82849b9bc added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3256

**Comment by CaselIT** [comment]
ugh, two changes were created on gerrit. we will need to manually clean it up

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 2565a5fd4b1940e92125e53aeaa731cc682f49bb of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 2565a5fd4b1940e92125e53aeaa731cc682f49bb added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3220

**Comment by CaselIT** [comment]
I've updated the master branch here on github to be the same as main and it now gerrit works correctly.

after this is merged i'll remove the old branch

**Comment by Morikko** [comment]
Sorry, I am still used to the `master` branch. I will pay attention for the next time.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

just a heads up, this patch looks good, it's just in a lower priority track for me for the moment as we've just entered official 2.0 development and we are getting that set up, while also fielding incoming bugs that are mostly dialect-related.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3220

**Comment by CaselIT** [comment]
> 
> 
> Sorry, I am still used to the `master` branch. I will pay attention for the next time.

the issue is that we forgot to remove it. No problem in any case :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3220

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3220 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3312 has been **merged**. Congratulations! :)

**Pull request closed without merging**
