### PR TITLE
Omit include of no longer existing files

### PR DESCRIPTION
**Pull request by icemac**
When installing `SQLAlchemy==1.2.15` I get the following output:

```
Getting distribution for 'SQLAlchemy==1.2.15'.
warning: no files found matching '*.jpg' under directory 'doc'
warning: no files found matching '*.mako' under directory 'doc'
warning: no files found matching 'distribute_setup.py'
warning: no files found matching 'sa2to3.py'
warning: no files found matching 'ez_setup.py'
```

Resubmit of zzzeek/sqlalchemy#491.

### CODE REVIEW

**Comment by zzzeek** [comment]
please forgive a little bit of noise here I'm trying to fix access for my new PR hooks

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get this PR into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Change has been squashed to Gerrit review: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1037

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck_openstack

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

I think neither of my CI jobs would run for this because they are looking for changes in lib/ or tests/

**Pull request closed without merging**
