### PR TITLE
Move the metadata for `setuptools` into `PEP 621`-compliant `pyproject.toml`

### PR DESCRIPTION
**Pull request by KOLANICH**
PEP 621 is a standardized backend-neutral format for storing package metadata.

### Description
I had moved the metadata for `setuptools` there. Other configs residing there are not moved yet.

### Checklist

This pull request is:
- [x] A short code fix
- [x] A new feature implementation

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

I'm personally -1 on this at the moment.

sqlalchemy is at least in part dependent on setuptools to install c-extensions, so we don't have any advantage by moving to pyproject

**Comment by zzzeek** [comment]
we could look into this for 2.1.  for 2.0 now that it's released I dont want to make major installation changes

**Comment by KOLANICH** [comment]
> so we don't have any advantage by moving to pyproject

<details>
<summary>A wall of offtop</summary>

It's not so for `sqlalchemy` (`setup.py` still fits `sqlalchemy` needs). It is for me. Yes, it is a conflict of interests, I had done this PR out of self-interest, not with "oh, I have nothing to do, so I will go and help a random project".

1. In order to simplify code in some of my tools (a package manager not relying on pypi, relying on git instead) we need eventually to migrate as much as possible from `setup.cfg`, `setup.py` and backend-specific sections in `pyproject.toml` into `PEP 621` sections (and the ones defined in further PEPs, we definitely need a PEP to define compilation of cexts).

2. Also it'd bring an immediate benefit in reliability (parsing `setup.cfg` relies on `setuptools`, and `setuptools` has a warning that API can be gone any moment, though it is unlikely to happen in near future).

3. `pyproject.toml` is a declarative metadata. In a long run we would like to prohibit code execution during wheel building. For now it is not possible for this project, but a Chinese proverb says that a road of thousands leagues starts with a single step.

</summary>

**Comment by KOLANICH** [comment]
>have been opened for this, to avoid the work of creating a PR. In any case this can stay open, I don't think there will be particular changes to the setup.cfg file in the v2 series

Thanks for the info.

>I thought PEP 517 solved most of the issues, as in "you parse pyproject then delegate to the tools specified there"

<details>
<summary>Yet another wall of offtop</summary>

Yes, it has solved, TBH. But sometimes we need to get some metadata before building a wheel. For example, if we have an URI of a repo on a known source code hosting system (GitHub, GitLab, BitBucket, SourceHut, Gitea...), we can get metadata of a package by constructing an URI to raw `pyproject.toml`, fetching it and parsing it, if the metadata is stored there. And this can be done without cloning the repo, building a wheel and invoking the build backend. If there is no `pyproject.toml` (we get 404), then we can assumme that the repo contains no python package. Of course we then can probe for `setup.cfg` and `setup.py` in those cases, but this will complicate the code. Or we can resolve cyclic dependencies automatically (currently that is not implemented and I use the hardcoded resolutions for some essential packages (`setuptools`, `flit_core`, `hatchling`, and their deps)), when a build backend depends (maybe indirectly) on a package, that needs that build backend to be built.
</details>

**Comment by CaselIT** [comment]
The current plan is to start 2.1 development by end of the year, so it should not be long before this can be merged.

Reminder mostly to myself: the github workflows do stuff to the `setup.cfg` file. Will need to check if they need to be updated to target pyproject instead

**Comment by zzzeek** [comment]
i love using pyproject toml.  it's pretty silly that setup.cfg is literally just for flake8, being held hostage

**Comment by CaselIT** [comment]
se should look into [ruff](https://github.com/astral-sh/ruff) to see if it supports all feature that we use

**Comment by zzzeek** [comment]
it absolutely doesn't, unfortunately, we use a lot of plugins including our own.  zimports is also based on flake8.    we can't move from flake8.

there's a flake8 extension to allow pyproject.toml config.  I dont recall what was wrong last time I looked at it.

**Comment by CaselIT** [comment]
The PR https://github.com/sqlalchemy/sqlalchemy/pull/10481 made extras PEP-685-compliant.
Previous extra use aliases in the setup.cfg, that apparently are not supported in the toml, so once we resurrect this one it should just duplicate the targets. Ref
- https://github.com/sqlalchemy/sqlalchemy/pull/10481#issuecomment-1765200169
- https://github.com/sqlalchemy/sqlalchemy/pull/10481#issuecomment-1765304821

**Comment by CaselIT** [comment]
it seems that they may be compatible using the syntax mentioned here: https://github.com/sqlalchemy/sqlalchemy/pull/10481#issuecomment-1766628311

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 4c74231886f9000bd4942ab4ebddecaa825023bd of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Failed to create a gerrit review, git squash against branch 'main' failed

**Comment by zzzeek** [comment]
we want to bring this one in, then bring #10481 on top.   however this needs to be updated to reflect recent changes in setup.cfg


      git diff e09516081162776b74cc682...44771ab0c32730d1ecefac21af setup.cfg

```diff
diff --git a/setup.cfg b/setup.cfg
index b797af4af..890aea977 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -16,11 +16,11 @@ classifiers =
     Operating System :: OS Independent
     Programming Language :: Python
     Programming Language :: Python :: 3
-    Programming Language :: Python :: 3.7
     Programming Language :: Python :: 3.8
     Programming Language :: Python :: 3.9
     Programming Language :: Python :: 3.10
     Programming Language :: Python :: 3.11
+    Programming Language :: Python :: 3.12
     Programming Language :: Python :: Implementation :: CPython
     Programming Language :: Python :: Implementation :: PyPy
     Topic :: Database :: Front-Ends
@@ -31,13 +31,11 @@ project_urls =
 [options]
 packages = find:
 include_package_data = True
-python_requires = >=3.7
+python_requires = >=3.8
 package_dir =
     =lib
 
 install_requires =
-    importlib-metadata;python_version<"3.8"
-    greenlet != 0.4.17;(platform_machine=='aarch64' or (platform_machine=='ppc64le' or (platform_machine=='x86_64' or (platform_machine=='amd64' or (platform_machine=='AMD64' or (platform_machine=='win32' or platform_machine=='WIN32'))))))
     typing-extensions >= 4.2.0
 
 [options.extras_require]
@@ -45,6 +43,7 @@ asyncio =
     greenlet!=0.4.17
 mypy =
     mypy >= 0.910
+    types-greenlet >= 2
 mssql = pyodbc
 mssql_pymssql = pymssql
 mssql_pyodbc = pyodbc
@@ -81,7 +80,6 @@ asyncmy =
 aiosqlite =
     %(asyncio)s
     aiosqlite
-    typing_extensions!=3.10.0.1
 sqlcipher =
     sqlcipher3_binary
 
@@ -135,13 +133,13 @@ requirement_cls = test.requirements:DefaultRequirements
 profile_file = test/profiles.txt
 
 # name of a "loopback" link set up on the oracle database.
-# to create this, suppose your DB is scott/tiger@xe.  You'd create it
+# to create this, suppose your DB is scott/tiger@free.  You'd create it
 # like:
 # create public database link test_link connect to scott identified by tiger
-# using 'xe';
+# using 'free';
 oracle_db_link = test_link
 # create public database link test_link2 connect to test_schema identified by tiger
-# using 'xe';
+# using 'free';
 oracle_db_link2 = test_link2
 
 # host name of a postgres database that has the postgres_fdw extension.
@@ -184,4 +182,4 @@ docker_mssql = mssql+pyodbc://scott:tiger^5HHH@127.0.0.1:1433/test?driver=ODBC+D
 oracle = oracle+cx_oracle://scott:tiger@oracle18c/xe
 cxoracle = oracle+cx_oracle://scott:tiger@oracle18c/xe
 oracledb = oracle+oracledb://scott:tiger@oracle18c/xe
-docker_oracle = oracle+cx_oracle://scott:tiger@127.0.0.1:1521/?service_name=XEPDB1
+docker_oracle = oracle+cx_oracle://scott:tiger@127.0.0.1:1521/?service_name=FREEPDB1

```

**Comment by CaselIT** [comment]
I'll take a look at this

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 4c74231886f9000bd4942ab4ebddecaa825023bd of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
**KOLANICH** has proposed a fix for this issue in the **main** branch:

**Move the metadata for `setuptools` into `PEP 621`-compliant `pyproject.toml`.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5028

**Comment by CaselIT** [comment]
I've updated this on gerrit

- [ ] Will need to create a release in the test pip to test that everything is working ok

**Comment by CaselIT** [comment]
> we want to bring this one in, then bring #10481 on top.

it doesn't seem to work if we order these this way. TOX seems unable to find the extra if defined in pyproject with underscore.

Given this pyproject:
```toml
postgresql_pg8000 = ["pg8000>=1.29.1"]
```
tox cannot find it. Tried both
```ini
postgresql: postgresql_pg8000
postgresql: postgresql-pg8000
```

using instead in pyproject
```toml
postgresql-pg8000 = ["pg8000>=1.29.1"]
```
tox can find it with either of these two options
```ini
postgresql: postgresql_pg8000
postgresql: postgresql-pg8000
```

**Comment by zzzeek** [comment]
first go does not seem to be going well :(

**Comment by CaselIT** [comment]
> ModuleNotFoundError: No module named 'greenlet'

seems an unrelated issue. will inverstigate

**Comment by CaselIT** [comment]
> so this is another bug I would assume that occurred from the greenlet refactor

this was implicitly fixed by https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5023 so let's just wait for that

**Comment by CaselIT** [comment]
tox automatically installs it because of this extra:
https://github.com/sqlalchemy/sqlalchemy/blob/86f335c29e9f4d9a8e2b28dd75301f28f5f9f4f1/tox.ini#L17

**Comment by CaselIT** [comment]
> > I've updated this on gerrit
> > ```
> > * [ ]  Will need to create a release in the test pip to test that everything is working ok
> > ```
> 
> running it here https://github.com/CaselIT/sqlalchemy/actions/runs/7142539071

trying again at https://github.com/CaselIT/sqlalchemy/actions/runs/7159190973

**Comment by CaselIT** [comment]
All seems fine now

**Pull request closed without merging**
