### PR TITLE
Fixes: #5395 Add 'exists' to SQLite's reserved keywords

### LINKED ISSUE #5395: Query crashes with syntax error on SQLite
The list of reserved words in sqlite does not contain the word "exists" as needed. So the following toy query

```python
session.query(Model.column.label('exists')).first()
```
crashes with

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "exists": syntax error
```

as  the keyword is not wrapped by quotes. See here https://github.com/sqlalchemy/sqlalchemy/blob/e1d4e59116bbf1a12bb6b3f57d33ddfc757d4567/lib/sqlalchemy/sql/compiler.py#L4288.

The list of reserved words must be updated. That is

```
diff --git a/lib/sqlalchemy/dialects/sqlite/base.py b/lib/sqlalchemy/dialects/sqlite/base.py
index 15d125ce0..a203e786e 100644
--- a/lib/sqlalchemy/dialects/sqlite/base.py
+++ b/lib/sqlalchemy/dialects/sqlite/base.py
@@ -1334,6 +1334,7 @@ class SQLiteIdentifierPreparer(compiler.IdentifierPreparer):
             "escape",
             "except",
             "exclusive",
+            "exists",
             "explain",
             "false",
             "fail",
```
**Have a nice day!**

### PR DESCRIPTION
**Pull request by theosotr**
Fixes: https://github.com/sqlalchemy/sqlalchemy/issues/5395

**Have a nice day!**

### CODE REVIEW

**Review by CaselIT — APPROVED** [review]

**Comment by zzzeek** [comment]
that's the idea.   there's a reserved word test where we can add this word at: https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/test_sqlite.py#L626

if submitter can add a line to that file here I will pull the PR into CI.

then we need to do changelog file + backport to 1.3.

**Review by zzzeek — CHANGES_REQUESTED** [review]
please add this to https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/test_sqlite.py#L626 also thanks!

**Comment by theosotr** [comment]
done

**Comment by zzzeek** [comment]
> done

so quick!  ok

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 5608317a38db7b63115e3b467d182a3e5cc31580 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 5608317a38db7b63115e3b467d182a3e5cc31580: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2036

**Review by zzzeek — APPROVED** [review]

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2036

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2036 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2037

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2037 has been **merged**. Congratulations! :)

**Pull request closed without merging**
