### PR TITLE
icontains,istartswith,iendswith operators

### LINKED ISSUE #3482: `icontains`, `istartswith`, `iendswith`
**Migrated issue, originally created by jvanasco ([@jvanasco](https://github.com/jvanasco))**

discussed previously in 
* https://groups.google.com/forum/#!searchin/sqlalchemy/icontains/sqlalchemy/MUyt8zYaP0c/ht4fGR9q9w8J
* https://groups.google.com/forum/#!searchin/sqlalchemy/icontains/sqlalchemy/331XoToT4lk/RPjIYNTkSEIJ

I tried doing this myself, but don't know enough of the internals to get this done on my own.

it looks like these need to be modified

* sqlalchemy/sql/default_comparator.py
* sqlalchemy/sql/operators.py

but not sure about

* sqlalchemy/sql/compiler.py

there are probably more files.

if someone can get one working, I can do the rest and build out tests.

### PR DESCRIPTION
**Pull request by matiasrebori**
### Description
Sometimes we need to perform insensitive string comparison and even tho we could make it with `ILIKE` and `ILIKE wildcars`, heres a better implementation of this operators, improving the features of SQLAlchemy.
`Implemented with LIKE statement and lower() functions` using the example provided by @zzzeek in #3482 
### What has been done
Insensitive string comparison operators icontains,istartswith,iendswith including their respective tests. Builded over the operators contains, startswith and endswith.
### Issue 3482
Fixes #3482 

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [x] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Thanks for the effort,

I've just quickly browsed it before running the pipeline. Could you run black on the patch?

**Comment by matiasrebori** [comment]
> Thanks for the effort,
> 
> I've just quickly browsed it before running the pipeline. Could you run black on the patch?

i'm sorry i dont know what is to run black on the patch

**Comment by matiasrebori** [comment]
> > > Thanks for the effort,
> > > I've just quickly browsed it before running the pipeline. Could you run black on the patch?
> > 
> > 
> > i'm sorry i dont know what is to run black on the patch
> 
> no worries!

could you explain to me what it means?

**Comment by CaselIT** [comment]
you mean the "no worries!" comment? it's informal for "it's not a problem"

**Comment by jvanasco** [comment]
I like how this enables platform independence, but wonder if this should utilize ILIKE on platforms that support that command.

**Comment by matiasrebori** [comment]
> you mean the "no worries!" comment? it's informal for "it's not a problem"

im refering to the next sentence: run black on the patch.
its the first time i listen to

**Comment by matiasrebori** [comment]
> I like how this enables platform independence, but wonder if this should utilize ILIKE on platforms that support that command.

In terms of performance, i read that ILIKE has a lower performance vs LIKE with lower().

**Comment by CaselIT** [comment]
oh sorry I misread your first comment.

we use [black](https://github.com/psf/black) as formatter for the code, so I was asking to run it to re-format the code

**Comment by matiasrebori** [comment]
> oh sorry I misread your first comment.
> 
> we use [black](https://github.com/psf/black) as formatter for the code, so I was asking to run it to re-format the code

oh, now i understand haha, i will run black

**Comment by zzzeek** [comment]
> I like how this enables platform independence, but wonder if this should utilize ILIKE on platforms that support that command.

we should make it do that in a subsequent release.   is ILIKE only postgresql?

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 7287e2c436959fac4fef022f359fcc73d1528211 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 7287e2c436959fac4fef022f359fcc73d1528211: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4068

**Comment by CaselIT** [comment]
> is ILIKE only postgresql?

from a quick search it seems so

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4068 has been **merged**. Congratulations! :)

**Pull request closed without merging**
