### PR TITLE
Added missing keywords for MySQL dialect

### PR DESCRIPTION
**Pull request by oscarbatori**
Add missing MySQL keywords.

### Description
Adds some missing keywords from the MySQL dialect. While it's hard to describe this as a documentation/typographical fix, there are no current test for presence of the correct keywords, nor a realistic way to implement them those tests.

### Checklist
This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by oscarbatori** [comment]
For reference this pull request does something similar with seemingly no need for testing:
https://github.com/sqlalchemy/sqlalchemy/pull/5539/files

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision db76e7f9d3a903cb4acf0309d57a14fe69948a0f of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change db76e7f9d3a903cb4acf0309d57a14fe69948a0f: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**Gord Thompson** (gordthompson) wrote:

Does this need a changelog entry?

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by zzzeek** [comment]
> **Gord Thompson** (gordthompson) wrote:
> 
> Does this need a changelog entry?
> 
> View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

yeah a quick one

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**Gord Thompson** (gordthompson) wrote:

Hmm. We got "Verified +1" but "sqla_alembic_gerrit/pyv=py37" shows a failure. Are the alembic tests "informational only"?

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

alembic-recheck

i think it's from the previous round of runs

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**Gord Thompson** (gordthompson) wrote:

Code-Review+1 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**Gord Thompson** (gordthompson) wrote:

Code-Review+1 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2357

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

thank you!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2357

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2357 has been **merged**. Congratulations! :)

**Pull request closed without merging**
