### PR TITLE
Fix up Python logging metadata

### LINKED ISSUE #7612: base logging helper function clobbers log message metadata
### Describe the bug

[`lib/sqlalchemy/engine/base.py` contains a logging helper function](https://github.com/sqlalchemy/sqlalchemy/blob/ff1ab665cb1694b85085680d1a02c7c11fa2a6d4/lib/sqlalchemy/engine/base.py#L133-L139):
```python
    def _log_info(self, message, *arg, **kw):
        fmt = self._message_formatter

        if fmt:
            message = fmt(message)

        self.engine.logger.info(message, *arg, **kw)
```
Using this function will cause all emitted log messages to contain the metadata `function='_log_info'` and `line=131`. This makes it harder to group and filter messages.

### To Reproduce

```python
import sqlalchemy.engine.base
import logging
from unittest import mock

formatter = logging.Formatter("%(asctime)s %(funcName)s:%(lineno)d: %(message)s")
syslog = logging.StreamHandler()
syslog.setFormatter(formatter)
logging.getLogger().addHandler(syslog)
logging.getLogger().setLevel(logging.INFO)
logger = logging.getLogger(__name__)

logger.info("Message with correct metadata")
            
mock_self = mock.Mock()
mock_self.engine.logger = logger
mock_self._message_formatter = None
sqlalchemy.engine.base.Connection._log_info(mock_self, "Metadata overwritten")
```

### Error

```
2022-01-25 10:09:48,658 <module>:12: Message with correct metadata
2022-01-25 10:09:48,658 _log_info:131: Metadata overwritten
```

### Versions

- OS: independent
- Python: independent
- SQLAlchemy: 1.4.6 and newer, haven't checked when this was introduced

### Additional context

I don't have a ready solution that allows retaining the metadata with a helper function (ie. it's not as simple as adding a `stacklevel=2` with the `warnings` module)

### PR DESCRIPTION
**Pull request by Anthchirp**
### Description

Log messages emitted via `sqlalchemy.engine.base` and `sqlalchemy.log` may
report incorrect function names and line numbers, as they may be based
off a helper function stack frame. Add, and increment, the `stacklevel`
keyword argument to function calls to ensure that helper functions are
not themselves visible in the log records.

Fixes #7612

Open questions:
I don't know in what context `sqlalchemy.log` is otherwise used. I'm not entirely convinced that the stacklevel logic implemented here is correct in _all_ cases.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by Anthchirp** [comment]
(rebased on top of last commit with passing tests)

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision a90461a181a212acc891d901ac61b3e8eb5f6ecb of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change a90461a181a212acc891d901ac61b3e8eb5f6ecb: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Thanks! Looks ok to me, it's just missing a changelig file in the 1_4 folde

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by Anthchirp** [comment]
@CaselIT I've added a changelog entry. The PR is aimed at the `main` branch though, so should the entry not be in the `2_0` directory?

**Comment by CaselIT** [comment]
> @CaselIT I've added a changelog entry. The PR is aimed at the `main` branch though, so should the entry not be in the `2_0` directory?

Since it's a small fix we will backport in the 1.4 series, so the changelog goes there. The backport can happen in gerrit.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision cf9567beb06680df320cb12dde1f15baa68e1eb5 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset cf9567beb06680df320cb12dde1f15baa68e1eb5 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

making python2 happy took some tries, but it seems fine now

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3566

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

new patch coming, this patch will fail on python 3.7 and also will fail on python 2.7 if normal logging is used instead of echo flag.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3566

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

there seem to be something broken somewhere, since we are getting huge callcount changes

  Adjusted function call count 399221 not within 15.0% of expected 301, platform 
  Adjusted function call count 614 not within 5.0% of expected 47, platform 

the change looks ok otherwise

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

same callcount changes

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3566

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

yeah that was one of the tests keeping the log level turned on.    the engine/connection/result use conditionals to not call log.info at all if the log level isn't there.  as you can see that's a big deal callcount-wise

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3566 has been **merged**. Congratulations! :)

**Pull request closed without merging**
