### PR TITLE
handle quoted_name instances separately in engine.reflection.cache (Fixes: #11687)

### PR DESCRIPTION
**Pull request by Masterchen09**
### Description

See #11687 for the details of the issue and my thoughts how to solve it. :-)

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by zzzeek — CHANGES_REQUESTED** [review]
thanks for finding this, the test case here needs to be significantly simplified into small single-test cases that are easy to follow.   A counter can be used to indicate if a particular string value was pulled from cache or not, start with this:


```diff
diff --git a/test/engine/test_reflection.py b/test/engine/test_reflection.py
index 003b457a5..2dd68e106 100644
--- a/test/engine/test_reflection.py
+++ b/test/engine/test_reflection.py
@@ -1,3 +1,4 @@
+import itertools
 import unicodedata
 
 import sqlalchemy as sa
@@ -12,6 +13,7 @@ from sqlalchemy import Index
 from sqlalchemy import inspect
 from sqlalchemy import Integer
 from sqlalchemy import MetaData
+from sqlalchemy import quoted_name
 from sqlalchemy import schema
 from sqlalchemy import select
 from sqlalchemy import sql
@@ -19,6 +21,7 @@ from sqlalchemy import String
 from sqlalchemy import testing
 from sqlalchemy import UniqueConstraint
 from sqlalchemy.engine import Inspector
+from sqlalchemy.engine.reflection import cache
 from sqlalchemy.testing import assert_raises
 from sqlalchemy.testing import assert_raises_message
 from sqlalchemy.testing import AssertsCompiledSQL
@@ -2494,3 +2497,47 @@ class IncludeColsFksTest(AssertsCompiledSQL, fixtures.TestBase):
             "SELECT b_1.x, b_1.q, b_1.p, b_1.r, b_1.s, b_1.t "
             "FROM b AS b_1 JOIN a ON a.x = b_1.r",
         )
+
+
+class ReflectionCacheTest(fixtures.TestBase):
+    @testing.fixture
+    def cache(self, connection):
+        dialect = connection.dialect
+        info_cache = {}
+        counter = itertools.count(1)
+
+        @cache
+        def get_cached_name(self, connection, name, **kw):
+            return next(counter)
+
+        def get_cache(name):
+            return get_cached_name(dialect, connection, name, info_cache=info_cache)
+
+        return get_cache
+
+
+    def test_single_string(self, cache):
+        # new value
+        eq_(cache("name1"), 1)
+
+        # same value, counter not incremented
+        eq_(cache("name1"), 1)
+
+    def test_multiple_string(self, cache):
+        # new value
+        eq_(cache("name1"), 1)
+
+        eq_(cache("name2"), 2)
+
+        eq_(cache("name1"), 1)
+        eq_(cache("name2"), 2)
+
+    def test_quoted_false_plus_string(self, cache):
+
+        eq_(cache(quoted_name("n1", quote=False)), 1)
+        eq_(cache("n1"), 2)
+
+        eq_(cache(quoted_name("n1", quote=False)), 1)
+        eq_(cache("n1"), 2)
+
+    # etc

```

**Comment by Masterchen09** [comment]
Whooops, I didn't noticed that there are multiple classes in test_reflection.py, I just assumed, that there would only be one class and added the test function at the end...

Great idea with the counter - we only want to check whether a value was pulled from cache or not and don't really care about what the returned value looks like...

I have used your template and implemented 29 different scenarios with string, quoted_name true/false, args, kwargs and some combinations of it. The last test (test_multiple_quoted_name_false_true_and_string_arg_and_kwarg) is probably a bit larger (too large?), but also combines all possibilities in a single test.

**Review by zzzeek — CHANGES_REQUESTED** [review]
OK, great, this is a lot of tests.  Here's a way we can cut the number of tests written out explicitly in half, by parameterizing the arg/kwarg thing in the fixture, can we do this also since this is lots of lines of code

```diff
diff --git a/test/engine/test_reflection.py b/test/engine/test_reflection.py
index 003b457a5..aa2b1585e 100644
--- a/test/engine/test_reflection.py
+++ b/test/engine/test_reflection.py
@@ -1,3 +1,4 @@
+import itertools
 import unicodedata
 
 import sqlalchemy as sa
@@ -12,6 +13,7 @@ from sqlalchemy import Index
 from sqlalchemy import inspect
 from sqlalchemy import Integer
 from sqlalchemy import MetaData
+from sqlalchemy import quoted_name
 from sqlalchemy import schema
 from sqlalchemy import select
 from sqlalchemy import sql
@@ -19,6 +21,7 @@ from sqlalchemy import String
 from sqlalchemy import testing
 from sqlalchemy import UniqueConstraint
 from sqlalchemy.engine import Inspector
+from sqlalchemy.engine.reflection import cache
 from sqlalchemy.testing import assert_raises
 from sqlalchemy.testing import assert_raises_message
 from sqlalchemy.testing import AssertsCompiledSQL
@@ -2494,3 +2497,58 @@ class IncludeColsFksTest(AssertsCompiledSQL, fixtures.TestBase):
             "SELECT b_1.x, b_1.q, b_1.p, b_1.r, b_1.s, b_1.t "
             "FROM b AS b_1 JOIN a ON a.x = b_1.r",
         )
+
+
+class ReflectionCacheTest(fixtures.TestBase):
+    @testing.fixture(params=["arg", "kwarg"])
+    def cache(self, connection, request):
+        dialect = connection.dialect
+        info_cache = {}
+        counter = itertools.count(1)
+
+        @cache
+        def get_cached_name(self, connection, name, **kw):
+            return next(counter)
+
+        def get_cache_arg(name):
+            return get_cached_name(
+                dialect, connection, name, info_cache=info_cache
+            )
+
+        def get_cache_kwarg(name):
+            return get_cached_name(
+                dialect, connection, name=name, info_cache=info_cache
+            )
+
+        if request.param == "arg":
+            yield get_cache_arg
+        elif request.param == "kwarg":
+            yield get_cache_kwarg
+        else:
+            assert False
+
+    def test_single_string(self, cache):
+        # new value
+        eq_(cache("name1"), 1)
+
+        # same value, counter not incremented
+        eq_(cache("name1"), 1)
+
+    def test_multiple_string(self, cache):
+        # new value
+        eq_(cache("name1"), 1)
+
+        eq_(cache("name2"), 2)
+
+        eq_(cache("name1"), 1)
+        eq_(cache("name2"), 2)
+
+    def test_quoted_false_plus_string(self, cache):
+
+        eq_(cache(quoted_name("n1", quote=False)), 1)
+        eq_(cache("n1"), 2)
+
+        eq_(cache(quoted_name("n1", quote=False)), 1)
+        eq_(cache("n1"), 2)
+
+    # etc
```

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 00b7acc414626c22747ed8225c85ec3edd0a2afa of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 00b7acc414626c22747ed8225c85ec3edd0a2afa: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5443

**Comment by Masterchen09** [comment]
I have updated the tests using your example - I have also applied the same logic to the quoted_name true/false combinations where it was possible to bring down the number of tests to nine while covering the same (or even more?) combinations than before.

For the last test it is not possible to reuse the cache fixture (?), because the combination with the args/kwargs is "fixed", therefore I have added the counter, etc. there again - not sure about this...

**Comment by zzzeek** [comment]
it's great.  thanks for doing that!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 43d94273a5b13a89226e60de4b958d5b4ac7ff78 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 43d94273a5b13a89226e60de4b958d5b4ac7ff78 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5443

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5443 has been **merged**. Congratulations! :)

**Pull request closed without merging**
