### PR TITLE
Updated SQLAlchemy documentation in index.rst

### PR DESCRIPTION
**Pull request by hashAbhiBytes**
### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by hashAbhiBytes** [comment]
Fixes: #<issue number>

**Review by CaselIT — CHANGES_REQUESTED** [review]
Hi, could you avoid white space changes and instead edit only the words that you want to change?

Thanks

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 4a11a6548d812b1f61739397a3ccaa331f76a494 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 4a11a6548d812b1f61739397a3ccaa331f76a494: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5612

**Comment by CaselIT** [comment]
will try salvaging something from this

**Pull request closed without merging**
