### PR TITLE
Document subquery inserts orm

### PR DESCRIPTION
**Pull request by sonthonaxrk**
### Description

This documents what I think was undocumented but useful functionality. 

This pull request is:

- [x] A documentation / typographical error fix

### CODE REVIEW

**Review by CaselIT — APPROVED** [review]
looks good to me.

@zzzeek can you take a look?

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 8731439c8b874d7d7e1478a1409951c635a2004d of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 8731439c8b874d7d7e1478a1409951c635a2004d: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2875

**Review by zzzeek — CHANGES_REQUESTED** [review]
the technique added here is IMO too specific and arbitrary to be in this part of the docs, which is meant to be a tutorial emphasizing only the most primary use cases.  instead, this example belongs here: https://docs.sqlalchemy.org/en/14/orm/persistence_techniques.html#embedding-sql-insert-update-expressions-into-a-flush   however there is already an example of using select() against an attribute to be flushed.

so perhaps in the tutorial we just have a "seealso" to the "additional persistence techniques" section at https://docs.sqlalchemy.org/en/14/orm/persistence_techniques.html#, add perhaps an intro section at the top of this page. I would assume the submitter hasn't seen this section before, so having it linked would be the most helpful thing.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

there's been no activity here, can reopen w/ requested changes

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2875

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2875 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
