### PR TITLE
Fix many spell glitches

### PR DESCRIPTION
**Pull request by lelit**
This affects mostly docstrings, except in orm/events.py::dispose_collection() where one parameter gets renamed: given that the method is empty, it seemed reasonable to me to fix that too.

Please tell me if you'd prefer dealing with more atomic commits, and will try to split this on the single words.

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 779ed75acb6142e1f1daac467b5b14134529bb4b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1 Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1096 has been **merged**. Congratulations! :)

**Comment by zzzeek** [comment]
a few long lines snuck in there since I've added pep8 but ill fix those separately

**Comment by zzzeek** [comment]
thanks!

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1 Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1116 has been **merged**. Congratulations! :)

**Comment by lelit** [comment]
Many thanks to you, it's always a pleasure!

**Pull request closed without merging**
