### PR TITLE
Fix the docstring of scoped_session.scalars

### PR DESCRIPTION
**Pull request by greyli**
### Description

This method was added in 1.4.26 instead of 1.4.24.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

That part of the file is generated from the method in `Session`, so it's hard to change that value only.
I guess we can add a note in the original method?

what do you think mike? @zzzeek

**Comment by zzzeek** [comment]
> Hi,
> 
> That part of the file is generated from the method in `Session`, so it's hard to change that value only. I guess we can add a note in the original method?
> 
> what do you think mike? @zzzeek

we should change it in session.py to include notes for both 1.4.24 and 1.4.26, referencing the specific class that was changed in each.  then that copies out via the code generation.

**Comment by greyli** [comment]
Updated. It will look like this:

image

Will the code be generated automatically when it's merged?

**Comment by CaselIT** [comment]
No, it's added by running `python tools/generate_proxy_methods.py`

I can run it if you want

**Comment by greyli** [comment]
> I can run it if you prefer

Thanks, that would be great. I tried, but the script throw this exception:

```
(venv) PS C:\Users\greyli\projects\sqlalchemy> python tools/generate_proxy_methods.py
importing module sqlalchemy.orm.scoping
Generating attributes for class scoped_session
Traceback (most recent call last):
  File "tools/generate_proxy_methods.py", line 431, in <module>
    main(cmd)
  File "tools/generate_proxy_methods.py", line 408, in main
    run_module(entry, cmd)
  File "tools/generate_proxy_methods.py", line 393, in run_module
    cmd.run_zimports(tempfile)
    self._run_console_script(
  File "C:\Users\greyli\projects\sqlalchemy\lib\sqlalchemy\util\tool_support.py", line 96, in _run_console_script
    raise Exception(
Exception: Could not find entrypoint console_scripts.zimports
```

Then I installed the `zimports` lib, now the error changed to:

```
importing module sqlalchemy.orm.scoping
Generating attributes for class scoped_session
Traceback (most recent call last):
  File "tools/generate_proxy_methods.py", line 431, in <module>
    main(cmd)
  File "tools/generate_proxy_methods.py", line 408, in main
    run_module(entry, cmd)
  File "tools/generate_proxy_methods.py", line 393, in run_module
    cmd.run_zimports(tempfile)
  File "C:\Users\greyli\projects\sqlalchemy\lib\sqlalchemy\util\tool_support.py", line 63, in run_zimports
    self._run_console_script(
  File "C:\Users\greyli\projects\sqlalchemy\lib\sqlalchemy\util\tool_support.py", line 112, in _run_console_script
    "import %s; %s.%s()" % (impl.module, impl.module, impl.attr),
AttributeError: 'EntryPoint' object has no attribute 'module'
```

**Comment by CaselIT** [comment]
Sure, will do later. Thanks for the effort so far

There is probably a minor version of python required to run that script. It's an internal tool, so it's not very polished :)

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 61132230cc6e897ab61beff25d98b19a4c0aefd0 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 61132230cc6e897ab61beff25d98b19a4c0aefd0: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4470

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4470 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4473 has been **merged**. Congratulations! :)

**Pull request closed without merging**
