### PR TITLE
Add "cube" and "lateral" to MySQL reserved words

### PR DESCRIPTION
**Pull request by StefanosChaliasos**
### Description
Add new MySQL reserved words; cube and lateral.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **jvanasco** to try to get revision 8c228be322023041b11691d93dafa1be090f01a0 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 8c228be322023041b11691d93dafa1be090f01a0: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2186

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

I cherry-picked this to rel_1_3 already as a test, but won't add a reviewer until the master is ironed out (this LGTM).

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2186

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

Code-Review-1

(1 comment)

super handy if you can do these, thanks!   need to move the rst file to 1.3 and re-cherry-pick to 1.3

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2186

* doc/build/changelog/unreleased_14/5539.rst (line 6): so when we're going to make a patch and also backport to 1.3, we put the changelog file in doc/build/changelog/unreleased_13/ .  that way it gets reported in the 1.3 changelog and also cherry-picks cleanly.

since 1.4 is not released yet, this does not need to be in the 1.4 changelog.

if we *did* want this to be both in the 1.3 *and* 1.4 changelogs, we *still* put the file in unreleased_13/ where it cherry-picks cleanly.  We add another directive ":versions: 1.4.x" for that use case, that's only for the period of time when 1.4 is released and we are still actively releasing 1.3 versions as well.

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

(1 comment)

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

* doc/build/changelog/unreleased_14/5539.rst (line 6): see the whole unreleased_14 folder was added here, we don't want that.

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

> super handy if you can do these, thanks!   need to move the rst file to 1.3 and re-cherry-pick to 1.3

I think I understand.

I'm happy to do these low-energy items in my spare time. Hopefully I'll get the hang of this quickly.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2186

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

Changed the source commit against master.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:



View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188 has been **restored**.  That means I can reopen this pull request!  Hooray :)

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

recheck openstack

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

i have no idea why patchset 4 failed. it may have been one of those tests that isn't stable?

cherrypicking the 1.4 onto rel_1_3 again was the only way i could figure out how to trigger a full test run.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

**Comment by zzzeek** [comment]
you can retrigger a test run by entering this comment:

recheck


for the openstack jobs

openstack-recheck

for the alembic jobs

alembic-recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2186

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2186 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+2

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2188 has been **merged**. Congratulations! :)

**Pull request closed without merging**
