### PR TITLE
Add pyproject

### LINKED ISSUE #5100: integrate `pyproject.toml`; deprecate `setup.cfg`
SqlAlchemy has adopted `black` code formatting, which is enforced by the `pre-commit` hook in the configuration file `.pre-commit-config.yaml` https://github.com/sqlalchemy/sqlalchemy/blob/master/.pre-commit-config.yaml

The usage of `black` requires it to be invoked with `-l 79` which is declared in .pre-commit-config.yaml (https://github.com/sqlalchemy/sqlalchemy/blob/master/.pre-commit-config.yaml#L8)

The `black` project specifically recommends configuration data be stored in `pyproject.toml` (https://black.readthedocs.io/en/stable/version_control_integration.html), which is the only configuration file consulted (https://black.readthedocs.io/en/stable/pyproject_toml.html and various rejected tickets on black's github)

Adopting a `pyproject.toml` file is something we should do to:

* more correctly store the `black` settings
* alert developers to know `black` is being used
* move towards new standards

Ideally we can do this in two phases:

* add pyproject.toml for `black`
* migrate `setup.cfg` items to `pyproject.toml`  

However there are two concerns (if not more):

1. It is unknown how various components that currently use `setup.cfg` will react to a `pyproject.toml` file being present. Mike recalls at least one might be.  The first phase could break the current build and test systems.

2. migrating from `setup.cfg` might also break things.

See Also:
* This ticket is a continuation of discussion from https://github.com/sqlalchemy/dogpile.cache/pull/169
* PEP 518 (https://www.python.org/dev/peps/pep-0518/) advocates `pyproject.toml` over `setup.cfg` for build configuration
* `setuptools` is considering a deprecation of "setup.cfg", however the period would be "forever"  (see https://github.com/pypa/setuptools/issues/1688)

### PR DESCRIPTION
**Pull request by CaselIT**
- Added pyproject.toml with black arguments
- Updated black version in precommit hook
- Reformatted the code

Fixes #5100

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by jvanasco** [comment]
@zzzeek posted this changeset for dogpile last night, where the black had an additional config line...

https://gerrit.sqlalchemy.org/#/c/sqlalchemy/dogpile.cache/+/1670/

**Comment by CaselIT** [comment]
The current configuration of sqlalchemy did not have it. I can add it to the configuration if needed

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 795fd5f896be4a07a2b18e6525674b815ac17593 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 795fd5f896be4a07a2b18e6525674b815ac17593: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1690

**Comment by CaselIT** [comment]
Thanks for completing this @zzzeek 🎉

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/1690

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1690 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/1691

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1691 has been **merged**. Congratulations! :)

**Pull request closed without merging**
