### PR TITLE
Remove print statement in favor of print() function in docs and examples

### PR DESCRIPTION
**Pull request by atugushev**
### Description

Remove print statements

### Checklist

This pull request is:

- [X] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
oh wow this is nice, thanks!

i have to run this through CI since it's pretty big, CI will check for any flake8 issues (line length).    will backport to 1.3 as well.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 04a7394f71298322188f0861b4dfe93e5485839d of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 04a7394f71298322188f0861b4dfe93e5485839d: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1746

**Review by CaselIT — APPROVED** [review]

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1746

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1746 has been **merged**. Congratulations! :)

**Comment by zzzeek** [comment]
thanks!

**Comment by atugushev** [comment]
@CaselIT @zzzeek thanks for reviewing and merging this PR 🙏

**Pull request closed without merging**
