### PR TITLE
Issue #4500 : Change StatementError formatting (newlines and %s)

### LINKED ISSUE #4500: Error Message Formatting : Missing Bind Parameter
Hey hey,

I'm just looking for comments/interest on changing the error formatting for `StatementError`. I'm interested in making small changes at the two lines below:
- Change `%r` to `%s` so that multi-line SQL statements appear formatted in a way that would be more quickly recognized by its author.

https://github.com/sqlalchemy/sqlalchemy/blob/4d7ac4be6c2f548b2e54d015003028bd9d10c805/lib/sqlalchemy/exc.py#L349

- Join on `"\n"` instead of `" "` in hopes of improved readability

https://github.com/sqlalchemy/sqlalchemy/blob/4d7ac4be6c2f548b2e54d015003028bd9d10c805/lib/sqlalchemy/exc.py#L356

For example, this makes the difference between the two error messages:

```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id' [SQL: 'select * from reviews where id = %(id)s'] (Background on this error at: http://sqlalche.me/e/cd3x)

(sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id' [SQL: 'select * from reviews where id = %(id)s'] (Background on this error at: http://sqlalche.me/e/cd3x)
```

becomes

```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id'
[SQL: (select * from reviews where id = %(id)s)]
(Background on this error at: http://sqlalche.me/e/cd3x)

(sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id'
[SQL: (select * from reviews where id = %(id)s)]
(Background on this error at: http://sqlalche.me/e/cd3x)
```

If this sounds alright. I'd be happy to make a PR :smile: 

Thanks for your time.

### PR DESCRIPTION
**Pull request by natec425**
This changes the error formatting for StatementError in two ways:

1) Break each error detail up over multiple newlines instead of
   spaced out on a single line. Hopefully, this helps readers scan
   the error message more easily.

2) Change the SQL representation in the message to use __str__ (%s)
   instead of the current behavior that uses __repr__ (%r). This
   should help readers recognize the structure of their SQL,
   particularly if it is a multiline SQL statement. In the multiline
   case, the SQL would be printed over multiple lines instead of
   printing an escaped "\n".

Fixes: #4500 

This pull request is:

- [X ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.

### CODE REVIEW

**Comment by zzzeek** [comment]
good looking PR.  let's run it through the blender.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 1bbcec147f0d692cd4022cecaef93d3c3231b034 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 1bbcec147f0d692cd4022cecaef93d3c3231b034: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1136

**Comment by zzzeek** [comment]
note you can keep pushing changes to the PR here if necessary, no need to learn gerrit unless you really felt like it.

**Comment by zzzeek** [comment]
it looks like some py27 unicode related issues were introduced, see https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=cext,db=sqlite-postgresql,pyv=py27/2235/.  can you work on these ?

**Comment by natec425** [comment]
Absolutely. I've got some family stuff today, but I'll get it in tonight.

**Comment by zzzeek** [comment]
great.  I have no idea what went wrong there but it's common that things break in that area (py27 related).

**Comment by natec425** [comment]
**I missed a ternary**
So I think 4 or the failures are coming from this ternary. 

https://github.com/sqlalchemy/sqlalchemy/blob/c0bd36873b3879747f2d094696fb0bc19c0539ff/test/engine/test_execute.py#L412-L420

In my PR I only updated 1 of the branches to test for `\n` instead of ` `.

Does that look right to you?

**I'm not sure about this `UnicodeDecodeError`**

I'm not super sure about this last failure: https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=cext,db=sqlite-postgresql,pyv=py27/2235/testReport/junit/test.dialect.test_suite/ExceptionTest_sqlite+pysqlite_3_7_17/test_exception_with_non_ascii/

I don't have a lot of experience with python2/3 compatibility, would you helping me out with this?

**Comment by zzzeek** [comment]
do you have a Python 2 interpreter installed?    for your proposal to the test_execute failure, you can confirm quickly just by running those tests:

# python2 -m pytest test/engine/test_execute.py

for the other issue , one side of the "details" setup is probably still a bytestring, where the "%r" was changed to a "%s".    The "self.statement" becoming a string likely needs to be coerced to unicode allowing for unicode errors (this is why %r is so safe to use).   In other places we've used this trick:  `("%r" % statement)[1:-1]` - this is available using the compat.decode_backslashreplace(statement, "utf-8") function you see elsewhere in exc.py.

**Comment by zzzeek** [comment]
let me know when you want me to run CI again (it's a manual process for me at the moment).

**Comment by natec425** [comment]
Ah. Gotcha.

So I ran the tests on Python 2.7.15rc1, but I still am only running on SQLite.

I think the first 4 failures (non `UnicodeDecodeError`) should be sorted out. The test case is passing on SQLite on my machine, and it was all from the same test case (`line 425, in test_stmt_exception_bytestring_raised`) with the same error message.

I couldn't make any progress on the `UnicodeDecodeError`. I tried changing `self.statement` to `compat.decode_replacebackslack(self.statement, "utf-8")` on this line but I still got the following failure.

https://github.com/natec425/sqlalchemy/blob/dc5d7b38706bdeddd2d4f82d119de556606f39cd/lib/sqlalchemy/exc.py#L349

```
________________________ ExceptionTest_sqlite+pysqlite_3_22_0.test_exception_with_non_ascii _________________________
Traceback (most recent call last):
  File "/home/nate/Projects/github.com/natec425/sqlalchemy/test/../lib/sqlalchemy/testing/suite/test_dialect.py", line 70, in test_exception_with_non_ascii
    err_str = str(err)
  File "/home/nate/Projects/github.com/natec425/sqlalchemy/test/../lib/sqlalchemy/exc.py", line 76, in __str__
    return self._sql_message(compat.py3k)
  File "/home/nate/Projects/github.com/natec425/sqlalchemy/test/../lib/sqlalchemy/exc.py", line 349, in _sql_message
    details.append("[SQL: %s]" % compat.decode_backslashreplace(self.statement, "utf-8"))
  File "/home/nate/Projects/github.com/natec425/sqlalchemy/test/../lib/sqlalchemy/util/compat.py", line 223, in decode_backslashreplace
    return text.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 8: ordinal not in range(128)
```

As far as when to run CI again, I don't want to tell you how to spend your resources :smile: . I don't know what else to do with the code right now though.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision dc5d7b38706bdeddd2d4f82d119de556606f39cd of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset dc5d7b38706bdeddd2d4f82d119de556606f39cd added to existing Gerrit review https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1136

**Comment by zzzeek** [comment]
new patchset up on the review: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1136/

however, my ISP has decided to crap out and my CI machines can't call out to gerrit or jenkins.   so, might have to wait for them to resolve that.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

pep8-recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

openstack-recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

recheck

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+1

so this is a change that needs to have a changelog file inside of doc/build/unreleased_13/4500.rst and also it should have a blurb inside of doc/build/changelog/migration_13.rst.   I usually do all that but if you feel like giving it a shot, that would be helpful.

**Comment by natec425** [comment]
I'll give it a go!

**Comment by natec425** [comment]
Added a draft of those two pieces. Hopefully it is helpful :smile:

**Comment by zzzeek** [comment]
OK, there is a logistical git thing we have to do here.    The reason I pull these PRs into gerrit is so that I can push my own changes to them; github has limited ability to allow this where you'd need to set some flag on your end and I'd rather not bother.

So, to get the tests to pass, I pushed up some changes to the github version.   For you to update here, you need to get my patch from here: 

https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1136/

specifically you can pull:

git pull https://gerrit.sqlalchemy.org/sqlalchemy/sqlalchemy refs/changes/36/1136/4

then check that out into a work branch (e.g. git checkout -b my_branch), then make your additional changes, then force-push back to your own repository (e.g. git push -f).  that will force this PR to reflect the latest everything.

**Comment by zzzeek** [comment]
Hmmmmm OK well I can work with that :)

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 60cc0ee68dc96b8f483a60d37bcb26b6c6d53efe of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 60cc0ee68dc96b8f483a60d37bcb26b6c6d53efe added to existing Gerrit review https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1136

**Comment by natec425** [comment]
Sorry :upside_down_face:

I'm not super clear on exactly what you were expecting out of that. Should I have done something like amending my previous commit with the patch and then force pushing over it?

**Comment by zzzeek** [comment]
I just noticed we're looking for the SQL statement to have newlines rendered as newlines, the repr() thing I did to fix Py2K will break that, which means there must be tests missing to ensure this behavior works.  seeing if I can add one now.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

thanks for all the efforts on this!

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1136 has been **merged**. Congratulations! :)

**Pull request closed without merging**
