### PR TITLE
Fix regular expression for `SQLiteDialect.get_check_constraints`

### LINKED ISSUE #11832: `get_check_constraints` result changed in SQLAlchemy 2.0.33
### Describe the bug

In mlflow/mlflow, we use `inspector.get_check_constraints` when validating database table schemas. We found the result has changed in the latest release (2.0.33).

```python
import mlflow

mlflow.set_tracking_uri("sqlite:///mlruns.db")

with mlflow.start_run():
    pass

import sqlalchemy

engine = sqlalchemy.create_engine("sqlite:///mlruns.db")

inspector = sqlalchemy.inspect(engine)

print(inspector.get_check_constraints("experiments"))
# 2.0.33:
# [{'sqltext': "lifecycle_stage IN ('active', 'deleted')), \n\tUNIQUE (name", 'name': 'experiments_lifecycle_stage'}]
# 2.0.32:
# [{'sqltext': "lifecycle_stage IN ('active', 'deleted')", 'name': 'experiments_lifecycle_stage'}]

# experiments table has a check constraint for `lifecycle_stage` and a unique constraint `name`. The 2.0.32 result looks correct while the 2.0.33 doesn't.
```

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

_No response_

### SQLAlchemy Version in Use

2.0.33

### DBAPI (i.e. the database driver)

sqlite

### Database Vendor and Major Version

sqlite

### Python Version

3.8

### Operating system

Linux

### To Reproduce

```python
See the code above
```

### Error

```
N/A
``` 

### Additional context

https://github.com/sqlalchemy/sqlalchemy/pull/11678 seems related

### PR DESCRIPTION
**Pull request by harupy**
### Description

Fix #11832

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by harupy** [comment]
@zzzeek Feel free to push commits to this PR.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision a10fcef45ccfad6ebf17ec94fc48d0965f0d4123 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change a10fcef45ccfad6ebf17ec94fc48d0965f0d4123: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5458

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5458 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5490 has been **merged**. Congratulations! :)

**Pull request closed without merging**
