### PR TITLE
fix(dialects.mysql): repeatedly exported DECIMAL

### PR DESCRIPTION
**Pull request by lvillis**
### Description

This is a typo, DECIMAL has been exported repeatedly, so this fix does not need to be tested.

https://github.com/sqlalchemy/sqlalchemy/blob/21ee595ba9ef3e7abc8982fac7bf488c904cf9c9/lib/sqlalchemy/dialects/mysql/__init__.py#L68
https://github.com/sqlalchemy/sqlalchemy/blob/21ee595ba9ef3e7abc8982fac7bf488c904cf9c9/lib/sqlalchemy/dialects/mysql/__init__.py#L71

```
# Intercepted code block
# sqlalchemy/lib/sqlalchemy/dialects/mysql/__init__.py

__all__ = (
    "BIGINT",
    "BINARY",
    "BIT",
    "BLOB",
    "BOOLEAN",
    "CHAR",
    "DATE",
    "DATETIME",
    "DECIMAL",   # Line 68
    "DOUBLE",
    "ENUM",
    "DECIMAL",   # Line 71
```

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 889d05c444264bf1b6d11386459d3360cc529d27 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 889d05c444264bf1b6d11386459d3360cc529d27: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3493

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

it's fine.  thanks!


1.4 backport is optional here

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3493

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3493 has been **merged**. Congratulations! :)

**Pull request closed without merging**
