### PR TITLE
capitalize author name

### PR DESCRIPTION
**Pull request by toh995**
Capitalized an author's name (i.e. `jonathan vanasco` => `Jonathan Vanasco`)

### Checklist
This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
cc @jvanasco I think you were in lowercase since the email name is lowercase

**Comment by jvanasco** [comment]
Lol. I saw this a few days ago when reviewing other PRs. Maybe I did that when lazy? Or maybe it got pulled off email? I wasn’t motivated to fix it myself and waste the Jenkins workload.

**Comment by zzzeek** [comment]
thank you!

**Comment by CaselIT** [comment]
> 
> 
> Lol. I saw this a few days ago when reviewing other PRs. Maybe I did that when lazy? Or maybe it got pulled off email? I wasn’t motivated to fix it myself and waste the Jenkins workload.

it got reported that way from git. from the commit message c3751983cbc4b6e55fa34f8b578dd9c2fc6bab38 the list was obtained with `git shortlog --summary | sort -r`

**Pull request merged**
