### PR TITLE
5667: Comments on (named) constraints

### PR DESCRIPTION
**Pull request by cheremnov**
Adds support for comments on named constraints, including `ForeignKeyConstraint`, `PrimaryKeyConstraint`, `CheckConstraint`, `UniqueConstraint`, solving the [Issue 5667](https://github.com/sqlalchemy/sqlalchemy/issues/5667). 

Supports only PostgreSQL backend.

### Description

Following the example of [Issue 1546](https://github.com/sqlalchemy/sqlalchemy/issues/1546), supports comments on constraints. Specifically, enables comments on _named_ ones — as I get it, PostgreSQL prohibits comments on unnamed constraints.

Enables setting the comments for named constraints like this:
```
Table(
   'example', metadata,
   Column('id', Integer),
   Column('data', sa.String(30)),
   PrimaryKeyConstraint(
       "id", name="id_pk", comment="id_pk comment"
    ),
   CheckConstraint('id < 100', name="cc1", comment="Id value can't exceed 100"),
   UniqueConstraint(['data'], name="uc1", comment="Must have unique data field"),
)
```

Provides the DDL representation for constraint comments and routines to create and drop them. Class `.Inspector` reflects constraint comments via methods like `get_check_constraints` .
### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
- [ ] A short code fix
- [x] A new feature implementation
	- Solves the issue 5667.
	- The commit message includes `Fixes: 5667`.
	- Includes tests based on comment reflection.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Great work. Let's add to gerrit so it can be reviewed

Regarding the reflection, for v2 the reflection for postgresql is being rewritten to support multi-reflection, but from a quick look it should not be too hard to support.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 3a55f9623fa77c2174b78fe0c87948bc2374244b of this pull request into gerrit so we can run tests and reviews and stuff

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 3a55f9623fa77c2174b78fe0c87948bc2374244b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by cheremnov** [comment]
> Great work. Let's add to gerrit so it can be reviewed
> 
> Regarding the reflection, for v2 the reflection for postgresql is being rewritten to support multi-reflection, but from a quick look it should not be too hard to support.

Sorry, can you please clarify whether I need to open a gerrit review? If so, how can I do this?

I followed gerrit instructions for pushing a new change to review, but to no avail.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 3a55f9623fa77c2174b78fe0c87948bc2374244b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 3a55f9623fa77c2174b78fe0c87948bc2374244b: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

**Comment by CaselIT** [comment]
The bot seems to have failed to create the gerrit. the first time, it seems that retrying did it
you can update this pr, then ping me or mike and we will make the bot update the gerrit

We probably should better document the workflow

**Comment by cheremnov** [comment]
> The bot seems to have failed to create the gerrit. the first time, it seems that retrying did it. you find it at the link you can update this pr, then ping me or mike and we will make the bot update the gerrit
> 
> We probably should better document the workflow

Thanks for the clarification!

Hopefully, fixed test regressions (tested on my computer):
1) Mock the response to the SQL request from `get_check_constraints` correctly: add the "comment" column.
2) Don't create tables for constraint comment tests if the tests are disabled.

Can you please update the gerrit? Thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 42a5d3c3e9ccf9a9d5397fd007aeab0854f66130 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 42a5d3c3e9ccf9a9d5397fd007aeab0854f66130 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

I've rebased this, moved the constraint ddl to postgresql and adapted reflection to the new code.

I've tested the performance impact of reflecting the comments and it seems negligible, but it would be great if you could also take a look mike.



View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

the fail on alembic is fixed in https://gerrit.sqlalchemy.org/c/sqlalchemy/alembic/+/3950 we probably should merge that first

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

now tests should all be green

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

a great job, solid.   mostly textual stuff and I think we might need to set .comment on ColumnCollectionConstraint._copy().

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

* doc/build/changelog/unreleased_20/5667.rst (line 9): Added support for comments on :class:`.Constraint` objects, including DDL and
reflection; the field is added to the base :class:`.Constraint` class and
corresponding constructors, however PostgreSQL is the only included backend to
support the feature right now. See parameters such as
:paramref:`.ForeignKeyConstraint.comment`,
:paramref:`.UniqueConstraint.comment`, :paramref:`.CheckConstraint.comment`.
* lib/sqlalchemy/engine/interfaces.py (line 894): .. versionadded: 2.0
* lib/sqlalchemy/engine/reflection.py (line 978): I'm a little torn if we should add "..versionadded:: 2.0 " to the docs for comment here.

Also...we could in theory replace these docs by pointing to docstrings for the typed dict class itself right?  might be nice to do that later.
* lib/sqlalchemy/sql/schema.py (line 3936): we need comment here too right?
* test/dialect/postgresql/test_reflection.py (line 2098): constraint
* test/dialect/postgresql/test_reflection.py (line 2135): comment  x 3

**Review by sqla-tester — COMMENTED** [review]
**Federico Caselli** (CaselIT) wrote:

updating

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

* lib/sqlalchemy/engine/reflection.py (line 978): are the typedict in the doc? if so we should definitely do that
* lib/sqlalchemy/sql/schema.py (line 3936): also maybe in the _copy?

**Review by sqla-tester — COMMENTED** [review]
**Federico Caselli** (CaselIT) wrote:

updated!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

* doc/build/changelog/unreleased_20/5667.rst (line 9): Done
* lib/sqlalchemy/engine/interfaces.py (line 894): Done
* lib/sqlalchemy/engine/reflection.py (line 978): it seems so. I'll clean them up in a follow up change
* lib/sqlalchemy/sql/schema.py (line 3936): Done
* test/dialect/postgresql/test_reflection.py (line 2098): Done
* test/dialect/postgresql/test_reflection.py (line 2135): Done

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

Ok you already fixed the mariadb issue. Let's see if rebasing helps

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

great job

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633

* lib/sqlalchemy/sql/schema.py (line 3936): oh right I missed a bunch more
* test/sql/test_metadata.py (line 3583): nice

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633 has been **merged**. Congratulations! :)

**Pull request closed without merging**
