### PR TITLE
fix changelog

### PR DESCRIPTION
**Pull request by CaselIT**
Noticed a typo in the last changelog. I think this should be ported to 1_3 also
### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
@zzzeek ping.

Do you prefer these on gerrit? we should probably setup a proper filter to the jenkins jobs to that they don't run when modifying just documentation

**Comment by zzzeek** [comment]
so what's happening now is that there's a huge list of PRs and a huge list of gerrits and I don't have a single integrated system of knowing whiuch ones are ready for review.   I guess it's a matter of a single search on gerrit and a single search on PRs here.

**Comment by CaselIT** [comment]
Not sure what would help.
We could use https://github.com/orgs/sqlalchemy/projects/1, but it's another place to keep in sync.

**Comment by zzzeek** [comment]
when i' look at the github list of PRs what visual cue tells me the ones that are awaiting my attention?  I guess all of them are

**Comment by CaselIT** [comment]
I guess we could have a label "for review". But that helps only if someone else set it, since users cannot add labels

**Comment by zzzeek** [comment]
cherry-picked to rel_1_3 as well

**Pull request merged**
