### PR TITLE
fix(6435): support `MemberExpr` for enum column declaration

### LINKED ISSUE #6435: mypy plugin detects Mapped[str] instead of Mapped[MyEnum] for enum column if the enum declaration is in a separate file
**Describe the bug**

mypy plugin detects `Mapped[str]` instead of `Mapped[MyEnum]` for enum column if the enum declaration is in a separate file

**Expected behavior**

Should detect the correct value: `Mapped[MyEnum]`

**To Reproduce**

* myenum.py:
```python
import enum

class MyEnum(enum.Enum):
    FOO = "foo"
    BAR = "bar"
```

* models.py:
```python
from sqlalchemy import Column
from sqlalchemy import Enum
from sqlalchemy.ext import declarative
from sqlalchemy.orm import Mapped

import myenum

class ModelBase:
    __abstract__ = True

Base = declarative.declarative_base(cls=ModelBase)

class User(Base):
    __tablename__ = "user"
    bar_or_foo: Mapped[myenum.MyEnum] = Column(Enum(myenum.MyEnum), nullable=False)
```

**Error**

`error: [SQLAlchemy Mypy plugin] Left hand assignment 'bar_or_foo: "MyEnum"' not compatible with ORM mapped expression of type "Mapped[str]"  [misc]`

**Versions.**
 - OS: Linux
 - Python: 3.9.5
 - SQLAlchemy: 1.4.18
 - Database: postgres
 - DBAPI:

### PR DESCRIPTION
**Pull request by hi-ogawa**
Fixes https://github.com/sqlalchemy/sqlalchemy/issues/6435

### Description

This PR changes mypy plugin's `extract_python_type_from_typeengine` so that it can also infer `Enum` type of the form `some_module.SomeEnum` (aka `MemberExpr` in mypy) in addition to currently supported `SomeEnum` (aka `NameExpr`).
Both `MemberExpr` and `NameExpr` are a child class of `RefExpr`, so this change looked very natural to me, even though I'm not particulary familar with mypy's internal.

In order to test a similar example to the original issue (it uses `import`), I added `__init__.py` under `test/ext/mypy/fiiles`, which might be a little bit odd. I believe I can test `MemberExpr` without actually using `import` (and thus without `__init__.py`), so if that's preferred, please let me know. I will remove it and change the testing strategy.

**Thanks for the code review!**

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

this change looks fine to me.

@zzzeek could you review?

**Comment by zzzeek** [comment]
nice, if it passes on jenkins we're good.


note that i am reconfiguring jenkins right now, will run this but it might fail for unrelated reasons. it will show the mypy job though

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 33a3dcd112b77600093890582f50ee7bb9b7c9b7 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 33a3dcd112b77600093890582f50ee7bb9b7c9b7: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3116

**Comment by zzzeek** [comment]
> Fixes #6435
> ### Description
> 
> This PR changes mypy plugin's `extract_python_type_from_typeengine` so that it can also infer `Enum` type of the form `some_module.SomeEnum` (aka `MemberExpr` in mypy) in addition to currently supported `SomeEnum` (aka `NameExpr`). Both `MemberExpr` and `NameExpr` are a child class of `RefExpr`, so this change looked very natural to me, even though I'm not particulary familar with mypy's internal.
> 
> In order to test a similar example to the original issue (it uses `import`), I added `__init__.py` under `test/ext/mypy/fiiles`, which might be a little bit odd. I believe I can test `MemberExpr` without actually using `import` (and thus without `__init__.py`), so if that's preferred, please let me know. I will remove it and change the testing strategy.

oh, we have a separate space for this, i thought it was there.  put the three test .,py files in test/ext/mypy/incremental/issue_6435/

**Comment by CaselIT** [comment]
> 
> 
> nice, if it passes on jenkins we're good.
> 
> note that i am reconfiguring jenkins right now, will run this but it might fail for unrelated reasons. it will show the mypy job though

we actually have a mypy job in the pr also, you see that in https://github.com/sqlalchemy/sqlalchemy/pull/7048/checks

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3116

**Comment by hi-ogawa** [comment]
Thanks for the review!

> oh, we have a separate space for this, i thought it was there. put the three test .,py files in test/ext/mypy/incremental/issue_6435/

Oh, that's nice, I totally overlooked that directory. In the last commit https://github.com/sqlalchemy/sqlalchemy/pull/7048/commits/59fced02a67b10c488cfbecb3ab15bdf18c47ec2, I just moved my test files into `mypy/incremental/ticket_6435`. I used `ticket_6435` instead of `issue_6435` since I thought that's what you meant. Please correct me if I'm wrong.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 59fced02a67b10c488cfbecb3ab15bdf18c47ec2 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 59fced02a67b10c488cfbecb3ab15bdf18c47ec2 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3116

**Review by sqla-tester — COMMENTED** [review]
Hi, this is **sqla-tester** and I see you've pinged me for review. However, user **hi-ogawa** is not authorized to initiate CI jobs.  Please wait for a project member to do this!

**Comment by hi-ogawa** [comment]
I just noticed `tox -e pep8` command. In the last commit https://github.com/sqlalchemy/sqlalchemy/pull/7048/commits/59f5c89688792f6af3b07488d5cf97f8f2e964dc, I fixed those errors.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 59f5c89688792f6af3b07488d5cf97f8f2e964dc of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 59f5c89688792f6af3b07488d5cf97f8f2e964dc added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3116

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3116 has been **merged**. Congratulations! :)

**Pull request closed without merging**
