### PR TITLE
Allow using AsyncEngine in compile

### PR DESCRIPTION
**Pull request by eltoder**
This works, so only need to update the type annotation.

This pull request is:

- [x] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed

### CODE REVIEW

**Review by zzzeek — CHANGES_REQUESTED** [review]
hi 

so far -1 on this because I didnt think you could pass an `AsyncEngine` to `compile()` like that.  Can you add a real unit test to confirm that works?

**Comment by CaselIT** [comment]
If async engine works it's likely that async connection does too.
If compile only uses the `dialect` attribute, maybe we could create a protocol to type this?

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision ba9e61a3902d5666a5176aedd50afe8ae7762bff of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change ba9e61a3902d5666a5176aedd50afe8ae7762bff: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5222

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5222 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5223 has been **merged**. Congratulations! :)

**Pull request closed without merging**
