### PR TITLE
pool logging documentation is wrong #4571

### PR DESCRIPTION
**Pull request by jaskirat1208**

### CODE REVIEW

**Comment by jaskirat1208** [comment]
Please review this PR, and suggest the changes :/

**Comment by zzzeek** [comment]
hi there -

im well aware it's here, and I have a very long backlog of work before I can get to everything in the queue, it may be days or weeks, thanks

**Comment by zzzeek** [comment]
OK, I want to make an additional edit but this is very nice, thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision e98ad34eca7e9f59fb07cd8b7ec317c1cb989848 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change e98ad34eca7e9f59fb07cd8b7ec317c1cb989848: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1183

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1 Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1183 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks much!!

**Pull request closed without merging**
