### PR TITLE
Fixed Improper Method Call: Removed `NotImplementedError`

### PR DESCRIPTION
**Pull request by nydelzaf**
## Discussion
[#10645](https://github.com/sqlalchemy/sqlalchemy/discussions/10645)

## Description
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [associationproxy.py](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/ext/associationproxy.py#L1980), class: _AssociationSet, there is a special method `__ixor__` that raises a NotImplementedError. If a special method supporting a binary operation is not implemented it should return [NotImplemented](https://docs.python.org/3/library/constants.html#NotImplemented). On the other hand, [NotImplementedError](https://docs.python.org/3/library/exceptions.html#NotImplementedError) should be raised from abstract methods inside user defined base classes to indicate that derived classes should override those methods. iCR suggested that the special method `__ixor__` should return NotImplemented instead of raising an exception. An example of how NotImplemented helps the interpreter support a binary operation is [here](https://docs.python.org/3/library/numbers.html#implementing-the-arithmetic-operations).

The same message is generated for `__imul__`, `__iand__`, `__isub__`, `__ior__` methods too.

## Changes
- Removed `NotImplementedError` according to [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions/10645)

## Previously Found & Fixed
- https://www.github.com/projecthamster/hamster/pull/737
- https://www.github.com/SciTools/iris/pull/5544
- https://www.github.com/cupy/cupy/pull/7900
- https://www.github.com/ethereum/web3.py/pull/3080

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

## CLA Requirements
*This section is only relevant if your project requires contributors to sign a Contributor License Agreement (CLA) for external contributions.*

All contributed commits are already automatically signed off.

> The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see [https://developercertificate.org/](https://developercertificate.org/) for more information).
\- [Git Commit SignOff documentation](https://developercertificate.org/)

## Sponsorship and Support
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.

The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

### CODE REVIEW

**Comment by CaselIT** [comment]
@zzzeek apparently we have something similar in the collection file, that does return NotImplemented
https://github.com/sqlalchemy/sqlalchemy/blob/900d13acb4f19de955eb609dea52a755f0d11acb/lib/sqlalchemy/orm/collections.py#L1452-L1538
Would it make sense to have the two parts behave the same way?

**Comment by zzzeek** [comment]
I think the NotImplemented should be removed from those too.  These were defensive decisions made way back in Python 2.3, 2.4 times

**Comment by CaselIT** [comment]
fine for me. The methods _set_binops_check_strict and _set_binops_check_loose could also be removed

**Comment by fazledyn-or** [comment]
@CaselIT In that case, let me remove `_set_binops_check_strict` and `_set_binops_check_loose` ASAP. Sounds okay?

**Comment by CaselIT** [comment]
> @CaselIT In that case, let me remove `_set_binops_check_strict` and `_set_binops_check_loose` ASAP. Sounds okay?

works for me

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 0b5c0d224dc40c1fdb6f56eae310eedc6dc74b28 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 0b5c0d224dc40c1fdb6f56eae310eedc6dc74b28: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4976

**Comment by zzzeek** [comment]
I need test cases established for AssociationSet which match what's being tested here: https://github.com/sqlalchemy/sqlalchemy/blob/44771ab0c32730d1ecefac21af13f113b1b19726/test/orm/test_collection.py#L869 

I dont think we need to copy out how test_collections.py works here, it's a very dense test suite, just tests for these methods to illustrate they raise TypeError in the same way , probably based on the use of `NotImplemented` as you originally proposed.    I'm just not 100% sure the assoc prox associationset is going to behave the same way here.

**Comment by fazledyn-or** [comment]
> I need test cases established for AssociationSet which match what's being tested here:
> https://github.com/sqlalchemy/sqlalchemy/blob/44771ab0c32730d1ecefac21af13f113b1b19726/test/orm/test_collection.py#L869
> 
> I dont think we need to copy out how test_collections.py works here, it's a very dense test suite, just tests for these methods to illustrate they raise TypeError in the same way , probably based on the use of `NotImplemented` as you originally proposed. I'm just not 100% sure the assoc prox associationset is going to behave the same way here.

I've removed my last commit. Test for `orm/test_collection.py` is passing 100% now. I think that should be enough.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 62a86232f552b57aa4652bef7767346a1917ea01 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 62a86232f552b57aa4652bef7767346a1917ea01 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4976

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

superseded by https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5279

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4976

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4976 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

I've implemented tests in test_associationproxy in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5279 which revealed these checks also needed to be in ``__or__``, ``__sub__``, ``__and__``, ``__xor__`` for the TypeError to work correctly.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4976

**Pull request closed without merging**
