### PR TITLE
Fixes: #6529

### PR DESCRIPTION
**Pull request by yicheng47**
### Description
Fixed the automap's declarative import from sqlalchemy.orm instead from the deprecated ext.declarative package

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by CaselIT — COMMENTED** [review]
Thanks, this looks fine, it will probably just need zimports to be run and a change log message.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 46d40005eae51fd7423da66f6ad4072f65744c1c of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 46d40005eae51fd7423da66f6ad4072f65744c1c: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2841

**Comment by CaselIT** [comment]
> 
> 
> Thanks, this looks fine, it will probably just need zimports to be run and a change log message.

updated the changeset on gerrit

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

thanks for your contribution!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2841

**Comment by jason3gb** [comment]
> > Thanks, this looks fine, it will probably just need zimports to be run and a change log message.
> 
> updated the changeset on gerrit

Hi, It's my first pr in this community and I'm not quite sure about the development process. Is it going to be merged automatically afterwards, and sync from gerrit to github? Or do I need to do any other modifications?

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2841 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

> Patch Set 2:
> 
> jason3gb@github wrote:
> 
> > > Thanks, this looks fine, it will probably just need zimports to be run and a change log message.
> > 
> > updated the changeset on gerrit
> 
> Hi, It's my first pr in this community and I'm not quite sure about the development process. Is it going to be merged automatically afterwards, and sync from gerrit to github? Or do I need to do any other modifications?

yes, it will be merged in gerrit and sync on github. no other change needed on your part. Thanks

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2841

**Pull request closed without merging**
