### PR TITLE
:pencil2: Fix repetition for same reference page on documentation

### PR DESCRIPTION
**Pull request by hunhoon21**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=pPDi4dT)

### Description

* "I removed unnecessary repetition in the documentation.
BADDFAB0-301C-4D70-8861-356350049E59

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

Thanks for the PR.
I'm not sure if mike intended to link two different sections here, since the ref are different.
Let's wait for his review. cc @zzzeek

**Review by zzzeek — CHANGES_REQUESTED** [review]
"section" singular

**Comment by zzzeek** [comment]
> Hi,
> 
> Thanks for the PR. I'm not sure if mike intended to link two different sections here, since the ref are different. Let's wait for his review. cc @zzzeek

it looks like I moved the labels to be on the same section when I did the queryguide rewrite.    I'll double check

**Comment by zzzeek** [comment]
OK confirmed these targets were moved from separate sections in inheritance_loading.rst to be the same section here, and that's 2.0 only

**Comment by hunhoon21** [comment]
To. @zzzeek 

I applied your suggestion via 0354ca1 !

**Review by CaselIT — APPROVED** [review]

**Pull request merged**
