### PR TITLE
Handle SSL SYSCALL error: Bad Address in postgresql/pyscopg2

### LINKED ISSUE #5387: psycopg2 unhandled SSL SYSCALL error: Bad address
**Describe the bug**

A connection returns `SSL SYSCALL error: Bad address` and gets into a bad state,
but it remains in the pool and continues to throw a series of
`DatabaseError: (psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq (Background on this error at: http://sqlalche.me/e/4xp6)`
errors until the entire container dies.

This may be a similar error to https://github.com/sqlalchemy/sqlalchemy/issues/3715

**Expected behavior**

The connection should be considered disconnected and taken out of the pool.
Should all `SSL SYSCALL`s be considered for disconnect? It seems like there's
a selection here:
https://github.com/sqlalchemy/sqlalchemy/blob/58ea811/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L969

**Initial Error**

```
...
  File "/src/benchling/configs/config_override.py", line 26, in get_all_tenant_configs
    return tenant.config_overrides
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 275, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 674, in get
    value = self.callable_(state, passive)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 708, in _load_for_state
    session, state, primary_key_identity, passive
  File "/src/benchling/lib/sqla_ext/session_eager_loader.py", line 189, in _emit_lazyload
    return super(SessionEagerLoader, self)._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 850, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 477, in all
    return list(self)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/ext/baked.py", line 380, in __iter__
    return q._execute_and_instances(context)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3106, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 91, in execute
    return self._trace_method(self.__wrapped__.execute, self._self_datadog_name, query, {}, query, *args, **kwargs)
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/psycopg/patch.py", line 51, in _trace_method
    return super(Psycopg2TracedCursor, self)._trace_method(method, name, resource, extra_tags, *args, **kwargs)
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 61, in _trace_method
    return method(*args, **kwargs)
DatabaseError: (psycopg2.DatabaseError) SSL SYSCALL error: Bad address
```

**Subsequent errors**
```
...
File "/src/benchling/lib/error_handlers.py", line 29, in error500
    db.session.rollback()
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 987, in rollback
    self.transaction.rollback()
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 557, in rollback
    util.reraise(*rollback_err)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 517, in rollback
    t[1].rollback()
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1697, in rollback
    self._do_rollback()
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1735, in _do_rollback
    self.connection._rollback_impl()
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 733, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    self.connection._rollback_impl()
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 733, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 731, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 486, in do_rollback
    dbapi_connection.rollback()
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 189, in rollback
    return self._trace_method(self.__wrapped__.rollback, span_name, {}, *args, **kwargs)
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 174, in _trace_method
    return method(*args, **kwargs)
DatabaseError: (psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq (Background on this error at: http://sqlalche.me/e/4xp6)
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 731, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/opt/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 486, in do_rollback
    dbapi_connection.rollback()
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 189, in rollback
    return self._trace_method(self.__wrapped__.rollback, span_name, {}, *args, **kwargs)
  File "/opt/venv/lib/python2.7/site-packages/ddtrace/contrib/dbapi/__init__.py", line 174, in _trace_method
    return method(*args, **kwargs)
DatabaseError: (psycopg2.DatabaseError) error with status PGRES_TUPLES_OK and no message from the libpq (Background on this error at: http://sqlalche.me/e/4xp6)
```

**Versions**
 - OS: Amazon Linux 2
 - Python: 2.7.17
 - SQLAlchemy: 1.2.17
 - Database: RDS postgres 9.6.9
 - DBAPI:

### PR DESCRIPTION
**Pull request by zeeeeeb**
### Description
Fixes: [5387](https://github.com/sqlalchemy/sqlalchemy/issues/5387)

Based on the conversation in the ticket, decided to just handle the Bad Address error, and not take the heavy handed approach for all SSL SYSCALL errors. Also added unit tests.

~~Also removing what does appear to be an obsolete message: `"losed the connection unexpectedly"`~~ <- left in per convo below.

### Checklist

-->

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
> 
> Also removing what does appear to be an obsolete message: `"losed the connection unexpectedly"`

OK well this message may be from a particular version of libpq.   We have support back to PG 9 and a little bit of PG 8, so I am not certain right now this message is actually obsolete.  we would have to track it down to be sure, otherwise removing this message introduces a small risk which seems unnecessary.

**Comment by zzzeek** [comment]
well here's the comment where i first wrote that code:

https://github.com/sqlalchemy/sqlalchemy/issues/516#issuecomment-441895678

then here is the commit:

c416dad6c652262baf

things were much more seat of the pants back then, i cant find the message being misspelled in libpq itself.  maybe it was an artifact of how the exception object stringified in psycopg2.  not sure.

**Comment by zkl2** [comment]
Fair enough; adding it back in just in case :+1:

**Comment by zzzeek** [comment]
im 99.9999% sure it's long obsolete but it's been there long enough to warrant its own change

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 66af76a107a22d9119edc8edcacc1e4ef66dc50d of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 66af76a107a22d9119edc8edcacc1e4ef66dc50d: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3102

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

looks great. 

needs:

1. a changelog file in doc/build/changelog/unreleased_14/

2. the "fixes" syntax is:

    Fixes: #1234

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3102

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3102 has been **merged**. Congratulations! :)

**Pull request closed without merging**
