### PR TITLE
glossary/association relationship: role->role_name

### PR DESCRIPTION
**Pull request by fpreiss**
### Description
In the glossary/association relationship section, the sql schema references `role_name`, the declarative mapping references `role_name`, however when adding employees to the project instead of `role_name` the undefined variable `role` is referenced.

P.S.: Additionally I stumbled upon a couple of inconsistencies for the code examples in the glossary. These are not code breaking in any way, but I feel the glossary would be more accessible if updated. In particular:

* The *many to many* snippet uses a Core Table Declaration for the `projects` relationship, whereas in the *association relationship* uses the ORM declarative style for the `employee_project` table
* In the *many to many* and *association relationship* examples we find snippets for adding some entries with the relationships to the table, while in *one to many* and *many to one* no such examples are given

Does this warrant a separate issue or are pull requests welcome here?

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
> Does this warrant a separate issue or are pull requests welcome here?

As you prefer. Documentation PR are easy to review and merge so it would not change much!

**Review by CaselIT — APPROVED** [review]

**Review by zzzeek — APPROVED** [review]
we should backport to 1.4 as well

**Comment by CaselIT** [comment]
With documentation I usually do

**Comment by fpreiss** [comment]
> > Does this warrant a separate issue or are pull requests welcome here?
> 
> As you prefer. Documentation PR are easy to review and merge so it would not change much!

Thanks for your feedback. Concerning the other points in the glossary, I prefer then to just give you PRs for review.

**Pull request merged**
