### PR TITLE
Update references to tables in PostgreSQL documentation

### PR DESCRIPTION
**Pull request by lpsinger**
### Description
The table numbers in the PostgreSQL documentation change from version to version. Update the table numbers for PostgreSQL 14 (the latest version, as of this writing) and use a fixed URL for that version.

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by CaselIT — CHANGES_REQUESTED** [review]
I think we could call the table by name instead of number.

So I would replace "Table 9-53" with "Range Operators Table" so we hopefully avoid chasing down the number every time a new pg release is released

**Comment by lpsinger** [comment]
> I think we could call the table by name instead of number.
> 
> So I would replace "Table 9-53" with "Range Operators Table" so we hopefully avoid chasing down the number every time a new pg release is released

@CaselIT: done.

**Review by CaselIT — APPROVED** [review]
Thanks!

**Comment by CaselIT** [comment]
sorry, this was forgotten here.

**Comment by CaselIT** [comment]
merged in 9d837b02b5eb42385281b88d09fe2aeea0376ca9 

not sure why github did not close this.

**Pull request closed without merging**
