### PR TITLE
Fixes #8066: Handle dead-connection errors for users of python-oracledb

### PR DESCRIPTION
**Pull request by cjbj**
### Description

The major release of the Oracle Database driver cx_Oracle that followed version 8.3 was renamed [python-oracledb 1.0](https://medium.com/@cjones-oracle/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).  It was tested with the SQLAlchemy test suite.  Until SQLAlchemy natively supports this namespace, user applications can add these lines in the first executed file to use python-oracledb instead of cx_Oracle:

    import sys
    import oracledb
    oracledb.version = "8.3.0"
    sys.modules["cx_Oracle"] = oracledb

See this [blog](https://medium.com/@cjones-oracle/using-python-oracledb-1-0-with-sqlalchemy-pandas-django-and-flask-5d84e910cb19).

This PR checks the new dead-connection error numbers that python-oracledb generates so that applications choosing to use python-oracledb have the same behaviors as with cx_Oracle.

There have been some brief mail discussions with @zzzeek about adding native support for the python-oracledb namespace to SQLAlchemy 2.0.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
the PR is likely harmless but the purpose is to push ahead so people would be using the new Oracle driver with SQLAlchemy 1.4, which is also fine, but on this end, 2.0 is where we're putting new things like real support for this Oracle driver.   There seems to be some urgency happening here and I'm a little hesitant to sign onto more urgency than we already have, which is quite plenty.

translation: i dont have a problem if this change comes out in 1.4 but I'm not ready to deal with new Oracle driver bug reports for 1.4.

**Comment by cjbj** [comment]
@zzzeek I understand the concern about support.  You can send any likely driver related issue in our direction.  

It would actually be helpful if SQLAlchemy users did start trying python-oracledb soon, so we can fix any driver problems - this is a major driver release and there are bound to be one or two things that need attention from us in the new Thin mode.  And perhaps there are things needed for SQLAlchemy 2.0 that could be learnt.

You weren't sure when 2.0 would land.  If this PR is merged,  I'd be more confident if I need to ask people to try the new driver with SQLAlchemy 1.4, and there is less urgency for a 2.0 release on our part.  A common situation when I might suggest people try the new driver is when they are having Instant Client install issues.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision d630b8457a1d29b7a1354ccc6d5e2956eea865f6 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change d630b8457a1d29b7a1354ccc6d5e2956eea865f6: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3881

**Comment by zzzeek** [comment]
just for sanity i want this in both branches for now

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3883 has been **merged**. Congratulations! :)

**Pull request closed without merging**
