### PR TITLE
Add missing `SmallInteger` column spec for `asyncpg`

### LINKED ISSUE #12170: `SmallInteger` is compiled to `SERIAL` instead of `SMALLSERIAL` on table creation when `asyncpg` driver is used.
### Describe the bug

If you are trying to create a table with a primary column of `SmallInteger` and the asyncpg driver is used, it will be compiled to `SERIAL` rather than `SMALLSERIAL`.
This is because this type is not implemented as a column spec and `AsyncpgInteger` is used instead, and a check for `SmallInteger` in the code below will return `False`, this should be fixed in #12171.
https://github.com/sqlalchemy/sqlalchemy/blob/860ca0b9d21874d9827f7f37cd0c330436baefb4/lib/sqlalchemy/dialects/postgresql/base.py#L2202-L2207

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

_No response_

### SQLAlchemy Version in Use

2.0.36

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 16

### Python Version

3.12.7

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import SmallInteger, create_engine
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import Mapped, declarative_base, mapped_column
from sqlalchemy.schema import CreateTable

ASYNCPG_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost/postgres"
PSYCOPG_SQLALCHEMY_DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost/postgres"
asyncpg_engine = create_async_engine(ASYNCPG_SQLALCHEMY_DATABASE_URL)
psycopg_engine = create_engine(PSYCOPG_SQLALCHEMY_DATABASE_URL)

Base = declarative_base()


class TestTable(Base):
    __tablename__ = "test_table"

    id: Mapped[int] = mapped_column(SmallInteger(), primary_key=True, autoincrement=True)


def main():
    print(CreateTable(TestTable.__table__).compile(psycopg_engine))
    print(CreateTable(TestTable.__table__).compile(asyncpg_engine))


if __name__ == "__main__":
    main()
```

### Error

```
CREATE TABLE test_table (
        id SMALLSERIAL NOT NULL,
        PRIMARY KEY (id)
)

CREATE TABLE test_table (
        id SERIAL NOT NULL,
        PRIMARY KEY (id)
)
``` 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axd1x8a**
### Description
Adds missing column spec for `SmallInteger` in `asyncpg` driver, fixes #12170

### CODE REVIEW

**Comment by CaselIT** [comment]
Can you also add a test in dialects/pg/test_compiler or similar? It can just be something like in the issue where you use the CreateTable and check the output?

Thanks

**Comment by FeeeeK** [comment]
Yes, I will see what I can do. Am I right to assume, that if it isn't possible to check only resulting type, I can test against output of `.compile()`?

**Comment by CaselIT** [comment]
Yes, most tests in that module should do that. There is an utility function that you can use. It should be easy base this test on what's already there

**Comment by CaselIT** [comment]
note that if you want us to take over it's fine too, just mention it! Thanks for the PR

**Comment by FeeeeK** [comment]
Hi, sorry it took so long, been busy with work. 
Found a test that should check this and it looks like it was only enabled for psycopg2. I removed that restriction and without my fixes it finds this error correctly.

**Comment by CaselIT** [comment]
No problem!

Good if there was already a test!

**Comment by CaselIT** [comment]
could you also add a changelog file here https://github.com/sqlalchemy/sqlalchemy/tree/main/doc/build/changelog/unreleased_20? the number refers to the issue, thanks!

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 82886d8521cb4e78822d685a864a9af438f6ea6b of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 82886d8521cb4e78822d685a864a9af438f6ea6b: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

**Comment by CaselIT** [comment]
that fail in the ci seems unrelated, so I will first try to fix it

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

recheck

a retest passed so we have to keep looking for this one

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

**Review by sqla-tester — COMMENTED** [review]
**Michael Bayer** (zzzeek) wrote:

ok found the bug

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

* test/dialect/postgresql/test_dialect.py (line 1621): this is where the patch breaks the psycopg dialects and registers the hstore handle globally

**Review by sqla-tester — COMMENTED** [review]
**Federico Caselli** (CaselIT) wrote:

fixed the test. also moved it to combinations

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

* test/dialect/postgresql/test_dialect.py (line 1621): Done

**Review by sqla-tester — COMMENTED** [review]
**Michael Bayer** (zzzeek) wrote:

code review left on gerrit

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

* test/dialect/postgresql/test_dialect.py (line 1603): we're creating the class for this type for every test case here even though it's only used in one of them.   I'd probably just put this class in the class body above here and use it directly in the combinations fixture

**Review by sqla-tester — COMMENTED** [review]
**Federico Caselli** (CaselIT) wrote:

code review left on gerrit

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

* test/dialect/postgresql/test_dialect.py (line 1603): gone with moving the class inside the if.

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

reckecl

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613 has been **merged**. Congratulations! :)

**Pull request closed without merging**
