### PR TITLE
MyPy extention: Support for setters - Handling functions defined in SQLAlchemy classes

### PR DESCRIPTION
**Pull request by HNygardStb**
### Description

When trying to run MyPy with SQLAlchemy plugin, I got the following stacktrace when running with "--show-traceback":

```
    /home/somewhere/someproject/models.py:82: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
    https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
    Please report a bug at https://github.com/python/mypy/issues
    version: 0.991
    Traceback (most recent call last):
      File "mypy/semanal.py", line 6047, in accept
      File "mypy/nodes.py", line 1143, in accept
      File "mypy/semanal.py", line 1435, in visit_class_def
      File "mypy/semanal.py", line 1511, in analyze_class
      File "mypy/semanal.py", line 1538, in analyze_class_body_common
      File "mypy/semanal.py", line 1616, in apply_class_plugin_hooks
      File "/home/somewhere/.cache/pypoetry/virtualenvs/env-name-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/mypy/plugin.py", line 258, in _base_cls_hook
        decl_class.scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
      File "/home/somewhere/.cache/pypoetry/virtualenvs/env-name-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 96, in scan_declarative_assignments_and_apply_types
        _scan_declarative_assignment_stmt(
      File "/home/somewhere/.cache/pypoetry/virtualenvs/env-name-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 386, in _scan_declarative_assignment_stmt
        assert isinstance(node, Var)
    AssertionError:
    /home/somewhere/someproject/models.py:82: : note: use --pdb to drop into pdb
```

The code at line 82 is

```
    # setter that sets a value automatically based on another field
    def account_number(self, account_number):
        self.previous_account_number = account_number - 1
```

Checking if node is mypy.nodes.FuncDef fixes the issue.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
hi - 

thanks for this!  however, we need an example of a python script that triggers it to add to the test suite.  otherwise this line of code is in danger of being reverted.

note the mypy extension is legacy as well.

**Comment by HNygardStb** [comment]
Hi! I've been trying to figure out the test setup of the extension during the day today. I've not succeed in that.

Any pointers to how to run the tests for it? 

My test class is this: 
```
from __future__ import annotations

import typing

from sqlalchemy import select
from sqlalchemy.ext.hybrid import hybrid_method
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class Base(DeclarativeBase):
    pass


class BankAccount(Base):
    __tablename__ = "bank_account"

    id: Mapped[int] = mapped_column(primary_key=True)
    nameNoSpace: Mapped[str] = mapped_column(String(100))
    nameDisplay: Mapped[str] = mapped_column(String(100))

    def nameDisplay(self, nameDisplay):
        self.nameNoSpace = nameDisplay.replace(" ", "_")

```

How can I run it with the old/new version of the extension?

**Comment by zzzeek** [comment]
easiest way is run a git checkout of SQLAlchemy, using a virtualenv with an editable install, or easier just set PYTHONPATH to where the checkout is (the lib/ folder).   Then you can "git checkout" between whatever branches you want.

however!   your test class is written in SQLAlchemy 2.0 style.   If you've updated your code to look like that example you gave, just turn off the mypy plugin altogether (and remove all old sqlalchemy stubs files).   it's not needed and will just get in the way.

**Comment by HNygardStb** [comment]
Yes. We mostly have a newer style of writing it, but are still on 1.4. I think we will drop turning on MyPy on build and try again after the upgrade to 2.0.

We have fixed the current MyPy errors by editing the extension locally. So some progress was made.

Thank you for responding and thank you for your work!

**Pull request closed without merging**
