### PR TITLE
Issue #5429 version 2: Patch Set A: internal test files

### LINKED ISSUE #5429: proposal: Standardize `isnot` & `notin_` operator names for SqlAlchemy2.0 (1.4?)
A handful of sql operators, as implemented in Python, are not consistent in SQLAlchemy.

The majority of items use a schema of `snake_case_with_trailing_underscore_` **when the sql command mimics Python reserved keywords**

For example, some of the commands adopting this scheme use:

| Python  | Sql | SQLAlchemy |
| ----- | ----- | ----- |
| and  | AND  | and_ |
| or  | OR  | or_ |
| is  | IS  |  is_ |
| in  | IS  |  in_ |

but compound operators either do not follow the same scheme, do not have an internal underscore, or both

| Python  | Sql | SQLAlchemy |
| ----- | ----- | ----- |
| is not  | IS NOT  | isnot |
| not in  | NOT IN  | notin_ |

This ticket will list them, and serve as reference to a PR if we proceed with any re-namings.

| SQLAchemy 1.3 | Proposed A | Proposed B (*rejected*) |
| ----- | ----- | ----- |
| isnot | is_not | is_not_ |
| notin_ | not_in | not_in_ |

If a change were to happen:
* the core function will be renamed
* the old function will be an alias for backwards compatibility; it will not be deprecated or warnings
* docs will be updated to use the new terms
* API docs for the old terms will state they are kept for backwards compatibility, and promote usage of the new terms

### PR DESCRIPTION
**Pull request by jvanasco**
Revised PR of #5501 

Patch Set A (1/2): Internal test files

This PR only handles the internal test library, and can be backported to 1.3

Fixes: #5429

### Checklist

This pull request is:
- [X] A new feature implementation

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision ede190219c7189a2cf354655a282d147cb89efdb of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by jvanasco** [comment]
Sorry, @zzzeek but it has been 5 hours and I can't get this to work with gerrit correctly. I'm not sure how to proceed.

The permissions on my git hooks got messed up, leading to no pre-commit/black AND no change-id being put in the commit messages.  Because there is no Change-ID in the messages, I can't push to gerrit - it just fails.  I tried creating a new branch and rebasing to generate a new change-id, but then `git review` complains about `10eadab normalize execute style for events, 2.0` not having a valid author, which is not related to this change.  

Gerrit is not my friend this week.

**Comment by zzzeek** [comment]
> Sorry, @zzzeek but it has been 5 hours and I can't get this to work with gerrit correctly. I'm not sure how to proceed.
> 
> The permissions on my git hooks got messed up, leading to no pre-commit/black AND no change-id being put in the commit messages. Because there is no Change-ID in the messages, I can't push to gerrit - it just fails. I tried creating a new branch and rebasing to generate a new change-id, but then `git review` complains about `10eadab normalize execute style for events, 2.0` not having a valid author, which is not related to this change.
> 
> Gerrit is not my friend this week.

I can push this up, however to the goal of fixing your checkout, you should see if you can create a brand new branch, and some kind of arbitrary commit, and see if Change-Id: gets in there.       Technically you don't even need the hooks, you could manually just add a Change-Id in there, and if I do "git commit --amend" a commit that  doesnt have a change-id, it adds one in.   that is, if the hook is working in the first place I've observed it to be fairly bulletproof so lets get your working directory in the right shape.  easiest way is move it aside and make a whole new working directory.

**Comment by jvanasco** [comment]
In #5523 (feature-5429-v2-a-testing), I did get a ChangeID in with an amend, then a `git push -f` into github.  

```
- commit ede190219c7189a2cf354655a282d147cb89efdb
- Author: jonathan vanasco <jonathan@2xlp.com>
- Date:   Thu Aug 20 15:16:20 2020 -0400
- 
-     Issue #5429 version 2: Patch Set A: internal test file
    
+ commit e2050606b83ec479c388c45bff0cc2153b8fd0b5
+ Author: jonathan vanasco <jonathan@2xlp.com>
+ Date:   Thu Aug 20 15:16:20 2020 -0400
+ 
+     Issue #5429 version 2: Patch Set A: internal test file
+     
+     Change-Id: I8350607544f3005b1afe3bfe4f27efd740e23e82    
```

I tried unsuccessfully to push into the gerrit ticket, but it wouldn't work.

Then I tried doing this all over again with only this branch in my checkout (I had the old ref stashed).  The `git review` worked, but started a new ticket. I can't seem to abandon the old ticket. 

```
- Gerrit 2169
+ Gerrit 2181
```

This is still failing, also because of the PEP8:

```
pep8 run-test: commands[0] | flake8 ./lib/ ./test/ ./examples/ setup.py doc/build/conf.py
./lib/sqlalchemy/testing/assertions.py:242:80: E501 line too long (82 > 79 characters)
./lib/sqlalchemy/testing/assertions.py:256:80: E501 line too long (82 > 79 characters)
```

If I run flake8 locally:

```
flake8 lib/sqlalchemy/testing

lib/sqlalchemy/testing/assertions.py:242:80: E501 line too long (82 > 79 characters)
lib/sqlalchemy/testing/assertions.py:256:80: E501 line too long (82 > 79 characters)
```

but look at black...

```
iiPPoodd:sqlalchemy jvanasco$ black lib/sqlalchemy/testing/assertions.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```

Why is this?

The default for black is supposed to be 88 characters (`max-line-length`)

* https://github.com/psf/black/blob/master/docs/compatible_configs.md
* https://github.com/psf/black/blob/205f3b67fbddc7ba0fa330c0493821e404451b82/src/black/__init__.py#L67
* https://github.com/psf/black/blob/537ea8df35b1004bdb228b483907fb5dd92e5257/docs/the_black_code_style.md

And we have set the black tool to use 79...

* https://github.com/sqlalchemy/sqlalchemy/blob/master/pyproject.toml

but for some reason, black is not using that 79 on my machine.  so I am going to spend some time figuring this out...

**Comment by jvanasco** [comment]
ah ha! it seems the issue is because black does not reformat comments, and the offending lines are comments!

**Comment by jvanasco** [comment]
closing to handle in Gerrit

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

abandoning in favor of another pull

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2169

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2169 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
