### PR TITLE
Switch badge provider

### PR DESCRIPTION
**Pull request by jeffwidman**
### Description
Switch badge provider to point at Pepy.tech which provides further stats on the downloads.

Also they use a blue color which better matches the blue color of the other badges. 😁

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by CaselIT** [comment]
for comparison the two are:
Current one:
[Downloads](https://pypi.org/project/sqlalchemy)

New one:
[Downloads](https://pepy.tech/project/sqlalchemy)

It seems that they also have the ability to personalize it https://pepy.tech/project/sqlalchemy/personalized-badge

I'm fine either way, @zzzeek do you have preferences?

**Comment by jeffwidman** [comment]
Also, to be clear, not something I feel strongly about at all, I just happened to notice the difference in badges while investigating what sort of badge to use on one of my personal OSS repos and thought I'd contribute it back when I noticed this new one offers interesting stats... but totally no sweat if you'd rather stick with what you've got.

**Comment by zzzeek** [comment]
what are people mostly using for python now?    pepy is useful but i never liked their site that much, can we just have a second badge that's customized pepy with the additional links?   

obv i dont want to keep switching every 6 months

**Comment by CaselIT** [comment]
Don't know what people are using now.
Do you have a suggestion on a custom badge mike?

**Comment by zzzeek** [comment]
usualy I like to just find nice usages of badges, so maybe poke around at django /pydantic / other fancy projects and see what they are doing

**Comment by CaselIT** [comment]
looked around:
- django, flask, psycopg: no barges
- pydanti: pepy https://github.com/pydantic/pydantic/
- fastapi: shields.io (but no download count)
- numpy: shields
- pandas: pepy
- polars: shileds
- asyncpg: shields

seems to be mixed use of one of the other.
since the other badges we have are blue, the new one is probably nicer

**Comment by CaselIT** [comment]
let's go with the new one, so we keep the colors the same

**Pull request merged**
