### PR TITLE
Issue #5429 version 2: Patch Set B: core library

### LINKED ISSUE #5429: proposal: Standardize `isnot` & `notin_` operator names for SqlAlchemy2.0 (1.4?)
A handful of sql operators, as implemented in Python, are not consistent in SQLAlchemy.

The majority of items use a schema of `snake_case_with_trailing_underscore_` **when the sql command mimics Python reserved keywords**

For example, some of the commands adopting this scheme use:

| Python  | Sql | SQLAlchemy |
| ----- | ----- | ----- |
| and  | AND  | and_ |
| or  | OR  | or_ |
| is  | IS  |  is_ |
| in  | IS  |  in_ |

but compound operators either do not follow the same scheme, do not have an internal underscore, or both

| Python  | Sql | SQLAlchemy |
| ----- | ----- | ----- |
| is not  | IS NOT  | isnot |
| not in  | NOT IN  | notin_ |

This ticket will list them, and serve as reference to a PR if we proceed with any re-namings.

| SQLAchemy 1.3 | Proposed A | Proposed B (*rejected*) |
| ----- | ----- | ----- |
| isnot | is_not | is_not_ |
| notin_ | not_in | not_in_ |

If a change were to happen:
* the core function will be renamed
* the old function will be an alias for backwards compatibility; it will not be deprecated or warnings
* docs will be updated to use the new terms
* API docs for the old terms will state they are kept for backwards compatibility, and promote usage of the new terms

### PR DESCRIPTION
**Pull request by jvanasco**
Revised PR of #5501 

Patch Set B (2/2): core files

This PR is a fork of Patch Set A (1/2), and deprecates the main library operators in favor of the newly standardized names

Fixes: #5429

### Checklist

This pull request is:
- [X] A new feature implementation

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 9f5dc2397aee219a2fc062bf864defaaab5b4946 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

Code-Review-1 Workflow-1

This needs to be redone because one of the commits does not have a change-id.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2170

**Comment by jvanasco** [comment]
closing to handle in Gerrit

**Comment by sqla-tester** [comment]
**Jonathan Vanasco** (jvanasco) wrote:

abandoning in favor of another pull

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2170

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2170 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
