### PR TITLE
add SQL Server 2017 to mssql/base.py - Fixes #4833

### LINKED ISSUE #4833: SQL Server 2017 (version 14) missing from mssql/base.py
It would go here:

https://github.com/sqlalchemy/sqlalchemy/blob/f499671ccc30cd42d6e3beb6ddec60e104bff9c5/lib/sqlalchemy/dialects/mssql/base.py#L697

### PR DESCRIPTION
**Pull request by gordthompson**
### Description
Add version 14 for SQL Server 2017 to mssql/base.py

Fixes #4833

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

### CODE REVIEW

**Comment by zzzeek** [comment]
can you create a one line issue and then add `Fixes: #<number>` to your commit (see second checkbox), thanks.   i'm not sure there are unit tests for this list alraedy so don't worry about that part.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 3d72335284fd585c40b961bbc7013e53f3874cb5 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 3d72335284fd585c40b961bbc7013e53f3874cb5: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1453

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Verified+1 Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1453 has been **merged**. Congratulations! :)

**Pull request closed without merging**
