### PR TITLE
Fix various source comment/doc typos

### PR DESCRIPTION
**Pull request by luzpaz**
### Description
Found via `codespell -q 3 -L ba,crate,datas,froms,gord,hist,inh,nd,selectin,strat,ue`

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed

### CODE REVIEW

**Comment by CaselIT** [comment]
That package seems interesting. Maybe we could add a pipeline gate to check if there are misspells.

Does it have a flag that just checks the code without writing and returns with a non-zero code if some change would be made?
like `black --check` https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#exit-code

**Comment by luzpaz** [comment]
@CaselIT haven't tested if [codespell](https://github.com/codespell-project/codespell) can do that. It seems doable nonetheless.

**Comment by CaselIT** [comment]
> 
> 
> @CaselIT haven't tested if [codespell](https://github.com/codespell-project/codespell) can do that. It seems doable nonetheless.

if you find a way of using it that way I think we can add it to the pipeline

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 0deac2219396bc0eba7da53eb3a80932edbf2dd7 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 0deac2219396bc0eba7da53eb3a80932edbf2dd7: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371

**Comment by CaselIT** [comment]
@zzzeek should this also be on 1_4 or 2_0 is fine?

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

I've added the codespell command to the tox pep8 env so that's run by the pipeline.

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371

**Comment by zzzeek** [comment]
we can keep in on 2.0 for now, I'd have to look to see what it is we are doing here

**Comment by CaselIT** [comment]
basically we run codespell after flake8 and black in the pep8 tox env. The idea is to catch spelling errors before merging :)

**Comment by zzzeek** [comment]
OK

guess that means all our variable names have to be nice_words_with_underscores also right?

**Comment by CaselIT** [comment]
it seems to be quite permissive, so not much needed to change.

I've added some skips in the setup.cfg config for some popular cases, but nothing major.

most changes are wont and cant to the ' versions

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371

**Review by sqla-tester — COMMENTED** [review]
**mike bayer** (zzzeek) wrote:

so this is definitely more than a documentation edit because it proposes that SQLAlchemy adopt the Codespell project into it's own CI.   I downloaded this patch and ran the pep8 tests and locally they failed, so im not sure how they passed on CI.

A few of the spelling changes here are incorrect so would need to be fixed, two changelog notes are actually showing a mis-spelling and there's a URL that was changed.   tooling here should not be trying to correct tokens inside of a URL.

overall we can accept the punctuation fixes and spelling fixes that are correct.  to adopt codespell would be a larger investment of time for us upfront to get it doing all the things without issues and adjusting to it, and that would push this off for us right now as getting 2.0 released is the priority.     





failures:

lib/sqlalchemy/util/langhelpers.py.orig:1895: wont ==> won't
lib/sqlalchemy/sql/selectable.py.orig:812: atttribute ==> attribute
lib/sqlalchemy/orm/strategy_options.py.orig:558: wont ==> won't
lib/sqlalchemy/dialects/postgresql/psycopg2.py.orig:1016: conenction ==> connection
test/requirements.py.orig:444: Cant ==> Can't
test/sql/test_types.py.orig:840: does't ==> doesn't
test/sql/test_deprecations.py.orig:254: overriden ==> overridden
test/sql/test_deprecations.py.orig:276: overriden ==> overridden
test/orm/test_update_delete.py.orig:252: critiera ==> criteria
doc/build/errors.rst.orig:1575: underyling ==> underlying
doc/build/orm/session_transaction.rst.orig:17: underyling ==> underlying
doc/build/orm/session_transaction.rst.orig:62: statment ==> statement
doc/build/orm/session_transaction.rst.orig:149: wih ==> with
ERROR: InvocationError for command /home/classic/dev/sqlalchemy/.tox/pep8/bin/codespell lib test doc examples (exited with code 65)
________________________________________________________________________ summary ________________________________________________________________________
ERROR:   pep8: commands failed


View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371

* doc/build/changelog/changelog_05.rst (line 2352): heh not like it matters..this was showing a typo fix :)
* doc/build/changelog/changelog_05.rst (line 3669): same
* doc/build/dialects/index.rst (line 129): this is wrong
* lib/sqlalchemy/orm/path_registry.py (line 316): this is fine but it's generally best to not do any variable name / code changes in a large patch that's otherwise all about documentation
* setup.cfg (line 130): there's way more words than this which would need to be excluded for this list to be useful, which is a much bigger list than would be feasible inside the setup.cfg file.  does the "codespell" tool support a separate file of ignore words?

also, are these full words in the source?  or only fragments?   "upto,ot,ons,ba,als,ser,nd,fo" etc. ?

**Comment by luzpaz** [comment]
Perhaps just accepting the PR and revisit adopting codespell after release?

**Comment by zzzeek** [comment]
yeah i'd rather do that for now

**Comment by CaselIT** [comment]
I'll update

**Review by sqla-tester — COMMENTED** [review]
**Federico Caselli** (CaselIT) wrote:

removed automation and fixed issues. I've reviewed all other and I think we are good now

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371

* doc/build/changelog/changelog_05.rst (line 2352): Ack
* doc/build/changelog/changelog_05.rst (line 3669): Ack
* doc/build/dialects/index.rst (line 129): Ack
* setup.cfg (line 130): we should definetly looking into that. I'll break this down into two

**Comment by sqla-tester** [comment]
**Federico Caselli** (CaselIT) wrote:

recheck

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3371 has been **merged**. Congratulations! :)

**Pull request closed without merging**
