### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by rockycookie**
Fixed two grammar mistakes

### Description

Fixed two grammar mistakes

### Checklist

This pull request is:

- [x] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [ ] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
the verb "represent" modifies the plural noun "classes".  "The classes represent X" vs. "The classes represents X".  if the "series" is making this ambiguous then the whole phrase should be restructured.

https://english.stackexchange.com/questions/123758/seller-and-purchaser-each-represents-or-seller-and-purchaser-each-represent

https://english.stackexchange.com/questions/12387/programs-that-each-perform-vs-programs-that-each-performs-which

**Comment by lukeZhangMengxi** [comment]
> the verb "represent" modifies the plural noun "classes". "The classes represent X" vs. "The classes represents X". if the "series" is making this ambiguous then the whole phrase should be restructured.
> 
> https://english.stackexchange.com/questions/123758/seller-and-purchaser-each-represents-or-seller-and-purchaser-each-represent
> 
> https://english.stackexchange.com/questions/12387/programs-that-each-perform-vs-programs-that-each-performs-which

I am still a little bit confused by the expression grammar. 
Would it be better if we say
```
The expression API consists of a series of classes, each class represents a particular database column.
```
?

**Comment by zzzeek** [comment]
hi can we use the phrase "each of which represent" ?

**Comment by lukeZhangMengxi** [comment]
> hi can we use the phrase "each of which represent" ?

Ehhh, feel like it should be "each of which represents".

References:
- https://www.spanishdict.com/examples/each%20of%20which
- https://ludwig.guru/s/each+of+which


> hi can we use the phrase "each of which represent" ?

Ehh, I feel like "each of which represents" is at least more used, if arguably correct.

References:
- https://ludwig.guru/s/each+of+which
- https://www.spanishdict.com/examples/each%20of%20which
- https://www.linguee.com/english-french/translation/each+of+which.html
- https://ell.stackexchange.com/questions/83127/each-of-them-is-or-each-of-them-are

**Comment by zzzeek** [comment]
hello from the future.   "each of which represents", fine can you push that up?   or I can, I know it's been months, sorry about that.

**Comment by lukeZhangMengxi** [comment]
> hello from the future. "each of which represents", fine can you push that up? or I can, I know it's been months, sorry about that.

Sure! I am honored to make my first contribute to the open source community!

**Comment by zzzeek** [comment]
thank you !

**Pull request merged**
