### PR TITLE
Allow to pass a version_id when inserting

### PR DESCRIPTION
**Pull request by LeResKP**
Same behaviour than in the update/delete

### CODE REVIEW

**Comment by CaselIT** [comment]
Hi,

What is the issue that this pr is trying to solve? Before opening a pr it's best practice to first open an issue to explain what is the problem.

**Comment by LeResKP** [comment]
Ah sorry, I was unsure.

Here is my use case:
I have a table like use_case (id, name, status, version_id)

I'm inserting a row
(id=1, name=Aurélien, status=PENDING) => which insert in the DB (id=1, name=Aurélien, status=PENDING, version_id=1) (it was already working)

I'm doing some update so the increment works
(name=Tod) => (id=1, name=Tod, status=PENDING, version_id=2)  (already working)

When I update the status, I want to insert a new using the 'make_transient' feature:
(name=Tod, status=ACCEPTED, version_id=3) =>  (id=2, name=Tod, status=ACCEPTED, version_id=1)
In this case I need to set the version_id, I don't want to start to 1 because of the insertion.

Let me know if it's not clear I can create a prototype with some assertions.

**Comment by CaselIT** [comment]
Thanks for the explanation.

**Comment by zzzeek** [comment]
is this issue specific to bulk_insert_mappings / bulk_save_objects() ?  that does not seem to make sense that you are trying to make use of make_transient() becasue that's not related to bulk_save_objects().    so...a quick MCVE of what you really need and that also would have to be expressed in the tests here, but ORM issues I generally get commtited within hours so some more formalized detail up front would be very helpful here thanks.

**Comment by LeResKP** [comment]
ok, sorry for this unclear pr.

I just wrote 2 scripts to expose my cases:

First one, I want to insert a new User row with a given version:
(it fails since my version passed is ignored by _collect_insert_commands)

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import attributes
from sqlalchemy.orm import backref
from sqlalchemy.orm import make_transient
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker


Base = declarative_base()

engine = create_engine("sqlite://", echo=False)

Session = sessionmaker(engine)


class User(Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    version = Column(Integer)
    status = Column(String(255))

    __mapper_args__ = {
        "version_id_col": version
    }


Base.metadata.create_all(engine)

session = Session()

# 1 - Simple use case, I'd like to pass the version when inserting a user
u1 = User(name='Tod', status='pending')
session.add(u1)
session.commit()

assert u1.version == 1

u2 = User(name='Fred', status='pending', version=2)
session.add(u2)
session.commit()

assert u2.version == 2  # Failing here since the version is ignore by _collect_insert_commands
```


Second one, I'm using make_transcient to create a new User row but I want to  increment the version. it's the same issue than my precedent script, the version set on the object is ignored.

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import attributes
from sqlalchemy.orm import backref
from sqlalchemy.orm import make_transient
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker


Base = declarative_base()

engine = create_engine("sqlite://", echo=False)

Session = sessionmaker(engine)

class Versioned(object):
    def new_version(self, session):
        # make us transient (removes persistent
        # identity).
        make_transient(self)

        # set 'id' to None.
        # a new PK will be generated on INSERT.
        self.id = None

@event.listens_for(Session, "before_flush")
def before_flush(session, flush_context, instances):
    for instance in session.dirty:
        if not isinstance(instance, Versioned):
            continue
        if not session.is_modified(instance):
            continue

        if not attributes.instance_state(instance).has_identity:
            continue

        # make it transient
        instance.new_version(session)
        # re-add
        session.add(instance)


class User(Versioned, Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    version = Column(Integer)
    status = Column(String(255))

    __mapper_args__ = {
        "version_id_col": version
    }

    def new_version(self, session):
        # create new version
        Versioned.new_version(self, session)
        # Increment the version even if we want to insert a new entry
        self.version += 1


Base.metadata.create_all(engine)

session = Session()
# 1 - Simple use case, I'd like to pass the version when inserting a user
u1 = User(name='Tod', status='pending')
session.add(u1)
session.commit()

assert u1.id == 1
assert u1.version == 1

u1.name = 'Fred'
session.commit()

assert u1.id == 2
assert u1.version == 2  # Failing here since the version is ignore by _collect_insert_commands
```

For both script it's the same issue during the insertion. Hope it's clearer now.

**Comment by zzzeek** [comment]
OK both of these cases are suited by configuring the mapper for a programatic version id generator.

both of your test cases pass if you set:

```
    __mapper_args__ = {
        "version_id_col": version,
        "version_id_generator": False
    }

```

then you need to make sure the initial version is 1 for your first insert:

    u1 = User(name='Tod', status='pending', version=1)

this general thing is documented at https://docs.sqlalchemy.org/en/13/orm/versioning.html#programmatic-or-conditional-version-counters

the thing you're doing in the second case looks like all of your UPDATEs are being turned into INSERTs, so you definitely would want to just set this flag, and in fact if you aren't doing any UPDATEs or DELETEs for real then it would appear to be unnecessary to use the "version_id_col" feature at all.   so the second case doesn't show a clear rationale for arbitrary overriding of version id on INSERT when auto-versioning is turned on.  you want to turn it off.

in the first case, it's not clear why you need to set the version id to "2" for a new object.   if these version ids are meaningful then you should stick to using your own programmatic approach.

**Comment by LeResKP** [comment]
Yes I understand, I already tried the version_id_generator to False but I'd also like to do some update. (I need the version_id_col to have consistency on update)

I just wrote another example with update and insert. I want to only do an insert if the status changes and update for all other updates.
But in my case I always want to increment the version.

Sorry to bother you, perhaps it's not the right way to do this, but I didn't found any other one.

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import inspect
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import attributes
from sqlalchemy.orm import backref
from sqlalchemy.orm import make_transient
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker


Base = declarative_base()

engine = create_engine("sqlite://", echo=False)

Session = sessionmaker(engine)

class Versioned(object):
    def new_version(self, session):
        # make us transient (removes persistent
        # identity).
        make_transient(self)

        # set 'id' to None.
        # a new PK will be generated on INSERT.
        self.id = None

@event.listens_for(Session, "before_flush")
def before_flush(session, flush_context, instances):
    for instance in session.dirty:
        if not isinstance(instance, Versioned):
            continue
        if not session.is_modified(instance):
            continue

        if not attributes.instance_state(instance).has_identity:
            continue

        # make it transient
        instance.new_version(session)
        # re-add
        session.add(instance)

class User(Versioned, Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    version = Column(Integer)
    status = Column(String(255))

    __mapper_args__ = {
        "version_id_col": version
    }

    def new_version(self, session):
        inspect_attrs = inspect(self).attrs
        if not inspect_attrs.status.history.has_changes():
            # The status hasn't changed, no need to do a version
            return

        # Check consitency
        res = session.query(self.__class__).filter_by(
            id=self.id, version=self.version).update(
                values=dict(version=self.version + 1),
                synchronize_session=False
            )
        if not res:
            raise exc.StaleDataError()

        # create new version
        Versioned.new_version(self, session)
        # Increment the version even if we want to insert a new entry
        self.version += 2

Base.metadata.create_all(engine)

session = Session()


u1 = User(name='Tod', status='approved')
session.add(u1)
session.commit()

assert u1.id == 1
assert u1.version == 1

u1.name = 'Fred'
session.commit()

assert u1.id == 1
assert u1.version == 2

u1.status = 'pending'
session.commit()

old_u1 = session.query(User).get(1)
assert old_u1.id == 1
assert old_u1.version == 3

assert u1.id == 2
assert u1.version == 4

u1.name = 'Tod'
session.commit()

assert u1.id == 2
assert u1.version == 5

u1.status = 'approved'
session.commit()

assert u1.id == 3
assert u1.version == 7
```

**Comment by zzzeek** [comment]
OK, so the thing is that you're already implementing your own version scheme, so it's best that you maintain control of it.   your test works if you just remember to increment the version by one for the UPDATE case:

```
    def new_version(self, session):
        inspect_attrs = inspect(self).attrs
        if not inspect_attrs.status.history.has_changes():
            # The status hasn't changed, no need to do a version
            self.version += 1
            return

```

your test runs completely as below.  since you have all this logic (which is based on my own recipes, I get it, this is still 99% code I wrote and I actually used it in production), adding an extra bump is not a big issue and it's clearer that the entire system is transparent in one place:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import attributes
from sqlalchemy.orm import make_transient
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker


Base = declarative_base()

engine = create_engine("sqlite://", echo=True)

Session = sessionmaker(engine)


class Versioned(object):
    def new_version(self, session):
        # make us transient (removes persistent
        # identity).
        make_transient(self)

        # set 'id' to None.
        # a new PK will be generated on INSERT.
        self.id = None


@event.listens_for(Session, "before_flush")
def before_flush(session, flush_context, instances):
    for instance in session.dirty:
        if not isinstance(instance, Versioned):
            continue
        if not session.is_modified(instance):
            continue

        if not attributes.instance_state(instance).has_identity:
            continue

        # make it transient
        instance.new_version(session)
        # re-add
        session.add(instance)


class User(Versioned, Base):
    __tablename__ = "user"

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    version = Column(Integer)
    status = Column(String(255))

    __mapper_args__ = {
        "version_id_col": version,
        "version_id_generator": False,
    }

    def new_version(self, session):
        inspect_attrs = inspect(self).attrs
        if not inspect_attrs.status.history.has_changes():
            # The status hasn't changed, no need to do a version
            self.version += 1
            return

        # Check consitency
        res = (
            session.query(self.__class__)
            .filter_by(id=self.id, version=self.version)
            .update(
                values=dict(version=self.version + 1),
                synchronize_session=False,
            )
        )
        if not res:
            raise exc.StaleDataError()

        # create new version
        Versioned.new_version(self, session)
        # Increment the version even if we want to insert a new entry

        self.version += 2


Base.metadata.create_all(engine)

session = Session()


u1 = User(name="Tod", status="approved", version=1)
session.add(u1)
session.commit()

assert u1.id == 1
assert u1.version == 1

u1.name = "Fred"
session.commit()

assert u1.id == 1
assert u1.version == 2, u1.version

u1.status = "pending"
session.commit()

old_u1 = session.query(User).get(1)
assert old_u1.id == 1
assert old_u1.version == 3

assert u1.id == 2
assert u1.version == 4

u1.name = "Tod"
session.commit()

assert u1.id == 2
assert u1.version == 5

u1.status = "approved"
session.commit()

assert u1.id == 3
assert u1.version == 7

```

**Comment by LeResKP** [comment]
Thks for your answer @zzzeek you opened my eyes :)

Next time I will open an issue. Before closing this pr, I have a last question please.

Here is another example

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import inspect
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import attributes
from sqlalchemy.orm import backref
from sqlalchemy.orm import exc
from sqlalchemy.orm import make_transient
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker


Base = declarative_base()

engine = create_engine("sqlite://", echo=False)

Session = sessionmaker(engine)

class Versioned(object):
    NEW_VERSION_PRIORITY = None

    def new_version(self, session):
        # make us transient (removes persistent
        # identity).
        make_transient(self)

        # set 'id' to None.
        # a new PK will be generated on INSERT.
        self.id = None


def sort_instance(instance):
    return 0
    if instance.NEW_VERSION_PRIORITY:
        return instance.NEW_VERSION_PRIORITY
    return instance.NEW_VERSION_PRIORITY


@event.listens_for(Session, "before_flush")
def before_flush(session, flush_context, instances):
    for instance in sorted(session.dirty, key=sort_instance):
        print(instance)
        if not isinstance(instance, Versioned):
            continue
        if not session.is_modified(instance):
            continue

        if not attributes.instance_state(instance).has_identity:
            continue

        # make it transient
        instance.new_version(session)
        # re-add
        session.add(instance)


class Child(Versioned, Base):
    NEW_VERSION_PRIORITY = 2

    __tablename__ = 'child'

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    version = Column(Integer, default=1)
    status = Column(String(255))

    parent_id = Column(
        Integer,
        ForeignKey('parent.id'),
        nullable=True
    )

    __mapper_args__ = {
        "version_id_col": version,
        "version_id_generator": False,
    }

    def new_version(self, session, force=False):
        if not force:
            inspect_attrs = inspect(self).attrs
            if not inspect_attrs.status.history.has_changes():
                self.version += 1
                return

        # Check consistency
        res = session.query(self.__class__).filter_by(
            id=self.id, version=self.version).update(
                values=dict(version=self.version + 1),
                synchronize_session=False
            )
        if not res:
            raise exc.StaleDataError()

        self.version += 2
        # create new version
        Versioned.new_version(self, session)


class Parent(Versioned, Base):
    NEW_VERSION_PRIORITY = 1

    __tablename__ = 'parent'

    id = Column(Integer, primary_key=True)
    name = Column(String(255))
    version = Column(Integer, default=1)
    status = Column(String(255))

    children = relationship(
        Child,
        backref=backref("parent", uselist=False),
    )

    __mapper_args__ = {
        "version_id_col": version,
        "version_id_generator": False,
    }

    def new_version(self, session):
        inspect_attrs = inspect(self).attrs
        if not inspect_attrs.status.history.has_changes():
            self.version += 1
            return

        children = self.children
        session.expire(self, ["children"])

        # Check consistency
        res = session.query(self.__class__).filter_by(
            id=self.id, version=self.version).update(
                values=dict(version=self.version + 1),
                synchronize_session=False
            )
        if not res:
            raise exc.StaleDataError()

        # create new version
        Versioned.new_version(self, session)

        self.children = []
        for child in children:
            child.new_version(session, force=True)
            self.children.append(child)

        self.version += 2

session = Session()

for i in range(5):
    print('ROUND %i' % i)
    Base.metadata.create_all(engine)

    p1 = Parent(name='p1', status='approved')
    c1 = Child(name='c1')
    c2 = Child(name='c2')
    p1.children = [c1, c2]

    session.add(p1)
    session.commit()

    assert p1.id == 1
    assert p1.version == 1

    p1.status = 'pending'
    with session.no_autoflush:
        p1.children[0].name = 'name'
    session.add(p1)
    session.commit()

    children = session.query(Child).all()
    assert len(children) == 4
    assert children[0].version == 2
    assert children[0].name == 'c1'
    assert children[1].version == 2
    assert children[1].name == 'c2'
    assert children[2].version == 3
    assert children[2].name == 'name'
    assert children[3].version == 3
    assert children[3].name == 'c2'

    assert p1.id == 2
    assert p1.version == 3

    assert p1.children[0].id == 3
    assert p1.children[0].version == 3
    assert p1.children[0].name == 'name'
    assert p1.children[1].id == 4
    assert p1.children[1].version == 3
    assert p1.children[1].name == 'c2'

    Base.metadata.drop_all(engine)
```

When I create a new version of parent I also want to create a new version of children. But if I also update the children I can't be sure about the order of the creation of the new version (parent vs children) since session.dirty is a set.

I added a function 
```
def sort_instance(instance):
    return 0
    if instance.NEW_VERSION_PRIORITY:
        return instance.NEW_VERSION_PRIORITY
    return instance.NEW_VERSION_PRIORITY
```

if you uncomment the return 0 it works but I'd like to know if there is a better way to have the priority according event.
In my case I'm doing
```
    p1.status = 'pending'
    with session.no_autoflush:
        p1.children[0].name = 'name'
```
So I assume it should create a new parent and children then update the child.

**Comment by zzzeek** [comment]
I would advise using the mapper-level before_insert() / before_update() events to set the final desired version ID on each instance.   these events are called in the order in which INSERT / UPDATE statements are emitted, so you would not have to set things like "priority" in order to resolve dependencies between rows.

**Comment by LeResKP** [comment]
perfect thks, I will have a look. Thks again.

**Pull request closed without merging**
