### PR TITLE
Fixes #3689

### LINKED ISSUE #3689: add public accessor for the pool._timeout value
**Migrated issue, originally created by Thomas Briles**

(edited by mike) in the form of a read-only Python descriptor with documentation.

### PR DESCRIPTION
**Pull request by irinade**
### Description

- The issue request to "add public accessor for the pool._timeout value" 
- mike bayer explained that timeout is on self.

- mike bayer also asked to replace == by eq_
### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- [ ] I have filed [a bug report](https://github.com/sqlalchemy/sqlalchemy/issues) which includes a complete [MCVE](http://stackoverflow.com/help/mcve) illustrating in simple code form the expected behavior and how the library deviates from it.   This is necessary **no matter how obvious the problem and/or fix is**, because this is how we track the issue being repaired for users that need to know about it, as well as where the correct fix can be agreed upon - the problem you are fixing is more often than not more complicated than it seems.
	- [x] My git commit includes a `Fixes: #<issue number>` comment with the above bug report number
	- [x] My code fix includes a unit test, which is typically based on the MCVE I did above
		- [ ] I then **ran the tests**, using the instructions at [README.unittests.rst](https://github.com/sqlalchemy/sqlalchemy/blob/master/README.unittests.rst)
	- [ ] I don't know how to write a test for this.    In which case please FILE A BUG ONLY.
	- Follow up availability:
		- [x] I **Will** be able to respond in a timely fashion to additional requests for changes and detail.
		- [ ] I **Will Not** be able to respond in a timely fashion to additional requests for changes and detail.
			- if you checked "Will Not", please FILE A BUG ONLY.
- [ ] A new feature implementation
	- [ ] I have filed [a bug report](https://github.com/sqlalchemy/sqlalchemy/issues) which includes a complete description of the new behavior, including an a Python code example that illustrates how the feature would work.
	- [ ] The new feature request was **approved by SQLAlchemy maintainers** who requested that I submit a pull request.
	- [ ] My git commit includes a `Fixes: #<issue number>` comment with the above bug report number
	- [ ] My code fix includes unit tests that assert the behavior is as expected.
		- [ ] I then **ran the tests**, using the instructions at [README.unittests.rst](https://github.com/sqlalchemy/sqlalchemy/blob/master/README.unittests.rst)
	- [ ] I don't know how to write the tests.  in which case please GET HELP FROM THE MAINTAINERS on the above mentioned issue how tests for this feature should be structured.
	- Follow up availability:
		- [ ] I **Will** be able to respond in a timely fashion to additional requests for changes and detail.
		- [ ] I **Will Not** be able to respond in a timely fashion to additional requests for changes and detail.
			- if you checked "Will Not", please FILE A BUG ONLY.

**Have a nice day!**

### CODE REVIEW

**Comment by zzzeek** [comment]
heya.  that's my new questionnaire :)

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 2e62a66aece19a464c9129fab7f915554f055769 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 2e62a66aece19a464c9129fab7f915554f055769: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1099

**Comment by zzzeek** [comment]
the single test added here still does not pass are you able to revise this ?

**Comment by irinade** [comment]
I removed assert in front of the eq_ function because the function already do an assert and return None which causes the error.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 0179b0a829e9609429dc698992670d2e6749c10c of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1099 has been **merged**. Congratulations! :)

**Pull request closed without merging**
