### PR TITLE
Type annotations for sqlalchemy.ext.mutable

### PR DESCRIPTION
**Pull request by ghost**
### Description

An attempt to annotate `lib/sqlalchemy/ext/mutable.py` with type hints (issue #8667).

This is a draft PR, so I'm hoping to get some help/guidance/validation from more knowledgeable people as I work on the PR. As for anyone interested in typing out the `sqlalchemy.ext.mutable` module or any one of [the modules that are left](https://github.com/sqlalchemy/sqlalchemy/issues/6810#issuecomment-1127062951) feel free to join me on the effort, hope we'll be able to figure things out together.

My type annotation strategy for the SQLAlchemy modules (as a noob):

- Take a look at [one of the already typed-out modules](https://github.com/sqlalchemy/sqlalchemy/issues/8667#issuecomment-1289035265) and compare it with the version from the 1.4 release and try to figure out the author's approach.
- See if you can [reuse old SQLAlchemy type stubs](https://github.com/sqlalchemy/sqlalchemy/issues/6810#issuecomment-975615809).
- Otherwise collect and apply runtime types from tests or doc examples (e.g. PyAnnotate)
- Generalize / amend whatever type hints you can manually
- Go through the documentation, tests, any examples and try to decide on the most appropriate type constraints for whatever that's left

Runtime type collection tools tried:

- MonkeyType
  - Fails at stubbing/annotating traced modules due to side effects of test suite imports.
- PyAnnotate
  - Fails at annotating traced modules due to references to nested types (class definitions within test functions) containing `<locals>` substring in their path.
  - The aforementioned problem is easily fixed by removing such substrings from the file containing traces before attempting to annotate the sources.

How to collect runtime types:

- Install [PyAnnotate](https://github.com/dropbox/pyannotate)
- [Update](https://github.com/dropbox/pyannotate/tree/master/example#alternative-using-pytest) `test/conftest.py`
- Run `pytest test/ext/test_mutable.py`
- Remove `<locals>` from `type_info.json`
  - This can be done with the following script

    ```py
    import json

    with open("type_info.json") as f:
        data = json.load(f)

    for trace in data:
        comments = []
        for comment in trace["type_comments"]:
            comments.append(comment.replace(".<locals>", ""))
        trace["type_comments"] = comments

    with open("./type_info.modified.json", "w") as json_file:
        json.dump(data, json_file)

    ```
- Apply type hints with `pyannotate -w lib/sqlalchemy/ext/mutable.py -3 --type-info type_info.modified.json`

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
  - Good to go, no issue or tests are needed
- [ ] A short code fix
  - please include the issue number, and create an issue if none exists, which
    must include a complete example of the issue. one line code fixes without an
    issue and demonstration will not be accepted.
  - Please include: `Fixes: #<issue number>` in the commit message
  - please include tests. one line code fixes without tests will not be accepted.
- [x] A new feature implementation
  - please include the issue number, and create an issue if none exists, which must
    include a complete example of how the feature would look.
  - Please include: `Fixes: #<issue number>` in the commit message
  - please include tests.

**Have a nice day!**

### CODE REVIEW

**Comment by g-kisenkov** [comment]
Ok, so for now I've just applied auto-generated type hints from running `pytest test/ext/test_mutable.py` and fixing some `pre-commit` errors. I'm planning to gradually generalize/correct the types the best I can and leave comments with justifications as to why I picked a concrete type for any tough / not-so-obvious cases.

**Comment by zzzeek** [comment]
hey -

thanks for this effort, this is a great start!

first thing is that the "test/" package is not part of the SQLAlchemy installed library, so there can't be any imports outside of "sqlalchemy" like that (also we use relative imports, but that can be fixed later).    For the case where you are using that test class, can we just create a Protocol there that matches what we need?

**Comment by g-kisenkov** [comment]
@zzzeek 

Ok, I did all I could. It's hard for me to see what exactly else could be done here, so I would be glad if you or someone else could review the code and let me know what's left to do. So far I've checked it with MyPy on every version from 3.7 through 3.11 and tried to refine the types I could. As for Protocols, chances are I'm just missing something, but I think every place where the classes from the tests were passed can be typed with just regular type hints so there's no need for defining Protocol types. 

All in all it was quite difficult for me to come up with meaningful type hints and the majority of the changes were probably made with the type checker leading me by the hand.

**Comment by zzzeek** [comment]
this looks great and I am sure is 95% of it, I can just finish it up as I would have to see what's not working and maybe fix things elsewhere in any case, it goes in under your commit regardless.     I'm not too avaiable this week so maybe next week.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision b907888ec67facc12dbdbccd6f2d9cd533b08a50 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change b907888ec67facc12dbdbccd6f2d9cd533b08a50: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4202

**Comment by zzzeek** [comment]
hey there -

this is REALLY GOOD, I am super impressed you got this whole thing strictly typed, all the imports are good, and it looks like you really dug deep into things, I am really impressed.    This stuff is very hard to work with and it looks like you spent a lot of time, thanks very much for that!      it passes mypy strict, this can go right in thanks!

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4202 has been **merged**. Congratulations! :)

**Pull request closed without merging**
