### PR TITLE
Sql

### PR DESCRIPTION
**Pull request by auvipy**
work in progress to clean sql module fully. single pr multiple individual commit for each change.

### CODE REVIEW

**Comment by zzzeek** [comment]
this probably needs some tests removed in test/sql/test_deprecations.py, let's run it and see

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 41e5f343aceff0c6c88d5afce87794af04cf6147 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 41e5f343aceff0c6c88d5afce87794af04cf6147: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1191

**Comment by zzzeek** [comment]
OK let me know when i should next send this to CI

**Comment by auvipy** [comment]
removal of related tests remains, will remove them ASAP

**Comment by zzzeek** [comment]
great stuff!

**Comment by zzzeek** [comment]
just FYI I think I want a lot of these removals to happen for 1.4 as well, I will be creating a 1.4 branch and backporting many removals

**Comment by auvipy** [comment]
OK great :dagger:

**Comment by zzzeek** [comment]
hey , i just pinged you on the issue someone started working on this as well in #4643 , and I believe I made a mistake in losing track of the work here so I apologize, so I need to figure out how to reconcile these two efforts.

we just need this stuff to be against master and broken up into smaller commits to slow things down a bit, should i leave you on task and tell @yuraff  to focus elsewhere or would @yuraff take over the efforts here?

**Comment by zzzeek** [comment]
cc @yurafff

**Comment by auvipy** [comment]
how much did he complete? my tasks were SQL modules only, so since git now has co-author option in the same commit/PR, I believe this won't be tough to integrate everyone's tasks

**Comment by zzzeek** [comment]
well I don't know, we have to see if they come back with an update, I haven't worked with this person before.

**Comment by auvipy** [comment]
Than I should push things forward. tell me what should be my next move? send this on master?

**Comment by auvipy** [comment]
Please feel free to assign me to these py2 and pre 1.1 deprecated features removals

**Comment by zzzeek** [comment]
I tried to do that the other day and I wasn't figuring it out.   OK so yes, if we can get small PRs against master, old deprecated things, that would be good.

**Comment by zzzeek** [comment]
oh.  Ok I can't add you or the other person as "assignee" on the issue itself unless you are in the org, I guess

**Comment by auvipy** [comment]
OK will do ASAP

**Comment by auvipy** [comment]
will resume work tomorrow

**Comment by zzzeek** [comment]
I think we should close this for now, and work on small PRs against master for the moment, then when I get 1.4 / master more solid ill work on rebasing things into rel_2_0, which I think I opened a little bit prematurely, as I realize most of what's in the plan right now is either for 1.4 or has a 1.4 element.

**Comment by auvipy** [comment]
yes, let's close it.

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1191 has been **abandoned**.  That means that at least for the moment I need to close this pull request. Sorry it didn't work out :(

**Pull request closed without merging**
