### PR TITLE
Added getter for query._execution_options

### PR DESCRIPTION
**Pull request by daniel--**
### Description

[This recipe](https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery) uses the private variable `query._execution_options`. This change adds a getter for this variable.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision acfbbe198ef675d3a41fb383cb173c3e6acdf652 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change acfbbe198ef675d3a41fb383cb173c3e6acdf652: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1112

**Comment by zzzeek** [comment]
this is great work!  found the right place for the tests and all that

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work to try to get revision 9674688bb5e80471a6a421bac06f995c2e64f8f7 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 9674688bb5e80471a6a421bac06f995c2e64f8f7 added to existing Gerrit review https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1112

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

Code-Review+2 Workflow+1

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/1112 has been **merged**. Congratulations! :)

**Pull request closed without merging**
