### PR TITLE
Rectify PG Range.__bool__, inverting previous logic

### PR DESCRIPTION
**Pull request by lelit**
The boolness of the range was defined to be equal to its emptiness. As this has been identified as a typo rather than the intended, this inverts the logic, to match common Python behaviour as well as how other popular PG drivers do.

### CODE REVIEW

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision 885068ec7b3fedd1052a7b1071fa84e81485dd6e of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 885068ec7b3fedd1052a7b1071fa84e81485dd6e: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4246

**Comment by lelit** [comment]
I'm willing to write also the changelog: how should I name it, given that there is no associated issue number?

**Comment by zzzeek** [comment]
> I'm willing to write also the changelog: how should I name it, given that there is no associated issue number?

in this case since nothing was released you can just edit the changelog we had in 8765.rst.

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 5670cdb920692a62f77b7b6ea312784033de83d9 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
Patchset 5670cdb920692a62f77b7b6ea312784033de83d9 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4246

**Comment by sqla-tester** [comment]
**mike bayer** (zzzeek) wrote:

looks great thanks!

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4246

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4246 has been **merged**. Congratulations! :)

**Pull request closed without merging**
